     Token        Matched       Row  ColStart    ColEnd

       INT            int         1         1         4
   ID_TEXT        getchar         1         5        12
      CHAR              (         1        12        13
      CHAR              )         1        13        14
      CHAR              ;         1        14        15
       INT            int         2         1         4
   ID_TEXT        putchar         2         5        12
      CHAR              (         2        12        13
       INT            int         2        13        16
   ID_TEXT             ch         2        17        19
      CHAR              )         2        19        20
      CHAR              ;         2        20        21
      VOID           void         4         1         5
   ID_TEXT         output         4         6        12
      CHAR              (         4        12        13
       INT            int         4        13        16
   ID_TEXT              n         4        17        18
      CHAR              )         4        18        19
      CHAR              {         5         1         2
        IF             if         6         5         7
      CHAR              (         6         8         9
   ID_TEXT              n         6         9        10
      CHAR              <         6        11        12
  CONSTINT              0         6        13        14
      CHAR              )         6        14        15
      CHAR              {         7         5         6
   ID_TEXT        putchar         8         9        16
      CHAR              (         8        16        17
 CONSTCHAR            '-'         8        17        20
      CHAR              )         8        20        21
      CHAR              ;         8        21        22
   ID_TEXT              n         9         9        10
      CHAR              =         9        11        12
      CHAR              -         9        13        14
   ID_TEXT              n         9        14        15
      CHAR              ;         9        15        16
      CHAR              }        10         5         6
      ELSE           else        11         5         9
        IF             if        11        10        12
      CHAR              (        11        13        14
   ID_TEXT              n        11        14        15
        EQ             ==        11        16        18
  CONSTINT              0        11        19        20
      CHAR              )        11        20        21
      CHAR              {        12         5         6
   ID_TEXT        putchar        13         9        16
      CHAR              (        13        16        17
 CONSTCHAR            '0'        13        17        20
      CHAR              )        13        20        21
      CHAR              ;        13        21        22
    RETURN         return        14         9        15
      CHAR              ;        14        15        16
      CHAR              }        15         5         6
       INT            int        16         5         8
   ID_TEXT            num        16         9        12
      CHAR              [        16        12        13
  CONSTINT             20        16        13        15
      CHAR              ]        16        15        16
      CHAR              ,        16        16        17
   ID_TEXT            idx        16        18        21
      CHAR              =        16        22        23
  CONSTINT              0        16        24        25
      CHAR              ;        16        25        26
     WHILE          while        17         5        10
      CHAR              (        17        11        12
   ID_TEXT              n        17        12        13
        NE             !=        17        14        16
  CONSTINT              0        17        17        18
      CHAR              )        17        18        19
      CHAR              {        18         5         6
   ID_TEXT            num        19         9        12
      CHAR              [        19        12        13
   ID_TEXT            idx        19        13        16
      CHAR              ]        19        16        17
      CHAR              =        19        18        19
   ID_TEXT              n        19        20        21
      CHAR              %        19        22        23
  CONSTINT             10        19        24        26
      CHAR              ;        19        26        27
   ID_TEXT              n        20         9        10
DIV_ASSIGN             /=        20        11        13
  CONSTINT             10        20        14        16
      CHAR              ;        20        16        17
       INC             ++        21         9        11
   ID_TEXT            idx        21        11        14
      CHAR              ;        21        14        15
      CHAR              }        22         5         6
       FOR            for        23         5         8
      CHAR              (        23         9        10
       DEC             --        23        10        12
   ID_TEXT            idx        23        12        15
      CHAR              ;        23        15        16
   ID_TEXT            idx        23        17        20
        GE             >=        23        21        23
  CONSTINT              0        23        24        25
      CHAR              ;        23        25        26
       DEC             --        23        27        29
   ID_TEXT            idx        23        29        32
      CHAR              )        23        32        33
   ID_TEXT        putchar        24         9        16
      CHAR              (        24        16        17
   ID_TEXT            num        24        17        20
      CHAR              [        24        20        21
   ID_TEXT            idx        24        21        24
      CHAR              ]        24        24        25
      CHAR              +        24        26        27
 CONSTCHAR            '0'        24        28        31
      CHAR              )        24        31        32
      CHAR              ;        24        32        33
      CHAR              }        25         1         2
       INT            int        27         1         4
   ID_TEXT          input        27         5        10
      CHAR              (        27        10        11
      CHAR              )        27        11        12
      CHAR              {        28         1         2
       INT            int        29         5         8
   ID_TEXT              n        29         9        10
      CHAR              =        29        11        12
  CONSTINT              0        29        13        14
      CHAR              ,        29        14        15
   ID_TEXT              t        29        16        17
      CHAR              =        29        18        19
   ID_TEXT        getchar        29        20        27
      CHAR              (        29        27        28
      CHAR              )        29        28        29
      CHAR              ;        29        29        30
     WHILE          while        30         5        10
      CHAR              (        30        11        12
 CONSTCHAR            '0'        30        12        15
        LE             <=        30        16        18
   ID_TEXT              t        30        19        20
      CHAR              &        30        21        22
   ID_TEXT              t        30        23        24
        LE             <=        30        25        27
 CONSTCHAR            '9'        30        28        31
      CHAR              )        30        31        32
      CHAR              {        31         5         6
   ID_TEXT              n        32         9        10
      CHAR              =        32        11        12
   ID_TEXT              n        32        13        14
      CHAR              *        32        15        16
  CONSTINT             10        32        17        19
      CHAR              +        32        20        21
   ID_TEXT              t        32        22        23
      CHAR              -        32        24        25
 CONSTCHAR            '0'        32        26        29
      CHAR              ;        32        29        30
   ID_TEXT              t        33         9        10
      CHAR              =        33        11        12
   ID_TEXT        getchar        33        13        20
      CHAR              (        33        20        21
      CHAR              )        33        21        22
      CHAR              ;        33        22        23
      CHAR              }        34         5         6
    RETURN         return        35         5        11
   ID_TEXT              n        35        12        13
      CHAR              ;        35        13        14
      CHAR              }        36         1         2
      VOID           void        38         1         5
   ID_TEXT           main        38         6        10
      CHAR              (        38        10        11
      VOID           void        38        11        15
      CHAR              )        38        15        16
      CHAR              {        39         1         2
       INT            int        40         2         5
   ID_TEXT          array        40         6        11
      CHAR              [        40        11        12
  CONSTINT              5        40        12        13
      CHAR              ]        40        13        14
      CHAR              ;        40        14        15
       INT            int        41         2         5
   ID_TEXT              a        41         6         7
      CHAR              ;        41         7         8
       INT            int        42         2         5
   ID_TEXT              b        42         6         7
      CHAR              ;        42         7         8
       INT            int        43         2         5
   ID_TEXT              c        43         6         7
      CHAR              ;        43         7         8
       INT            int        44         2         5
   ID_TEXT              d        44         6         7
      CHAR              ;        44         7         8
       INT            int        45         2         5
   ID_TEXT              e        45         6         7
      CHAR              ;        45         7         8
   ID_TEXT          array        46         2         7
      CHAR              [        46         7         8
  CONSTINT              0        46         8         9
      CHAR              ]        46         9        10
      CHAR              =        46        10        11
  CONSTINT              0        46        11        12
      CHAR              ;        46        12        13
   ID_TEXT          array        47         2         7
      CHAR              [        47         7         8
  CONSTINT              1        47         8         9
      CHAR              ]        47         9        10
      CHAR              =        47        10        11
  CONSTINT              1        47        11        12
      CHAR              ;        47        12        13
   ID_TEXT          array        48         2         7
      CHAR              [        48         7         8
  CONSTINT              2        48         8         9
      CHAR              ]        48         9        10
      CHAR              =        48        10        11
  CONSTINT              2        48        11        12
      CHAR              ;        48        12        13
   ID_TEXT          array        49         2         7
      CHAR              [        49         7         8
  CONSTINT              3        49         8         9
      CHAR              ]        49         9        10
      CHAR              =        49        10        11
  CONSTINT              3        49        11        12
      CHAR              ;        49        12        13
   ID_TEXT          array        50         2         7
      CHAR              [        50         7         8
  CONSTINT              4        50         8         9
      CHAR              ]        50         9        10
      CHAR              =        50        10        11
  CONSTINT              4        50        11        12
      CHAR              ;        50        12        13
   ID_TEXT              a        53         8         9
      CHAR              =        53        11        12
  CONSTINT             10        53        13        15
      CHAR              *        53        15        16
   ID_TEXT          array        53        16        21
      CHAR              [        53        21        22
  CONSTINT              0        53        22        23
      CHAR              ]        53        23        24
      CHAR              ;        53        24        25
   ID_TEXT              b        54         2         3
      CHAR              =        54         5         6
  CONSTINT              5        54         7         8
      CHAR              *        54         8         9
   ID_TEXT          array        54         9        14
      CHAR              [        54        14        15
  CONSTINT              1        54        15        16
      CHAR              ]        54        16        17
      CHAR              ;        54        17        18
   ID_TEXT              c        55         2         3
      CHAR              =        55         5         6
  CONSTINT              2        55         7         8
      CHAR              *        55         8         9
   ID_TEXT          array        55         9        14
      CHAR              [        55        14        15
  CONSTINT              2        55        15        16
      CHAR              ]        55        16        17
      CHAR              ;        55        17        18
   ID_TEXT              d        56         2         3
      CHAR              =        56         5         6
  CONSTINT             20        56         7         9
      CHAR              *        56         9        10
   ID_TEXT          array        56        10        15
      CHAR              [        56        15        16
  CONSTINT              3        56        16        17
      CHAR              ]        56        17        18
      CHAR              ;        56        18        19
   ID_TEXT              e        57         2         3
      CHAR              =        57         4         5
  CONSTINT             10        57         6         8
      CHAR              *        57         8         9
   ID_TEXT          array        57         9        14
      CHAR              [        57        14        15
  CONSTINT              4        57        15        16
      CHAR              ]        57        16        17
      CHAR              /        57        17        18
   ID_TEXT          array        57        18        23
      CHAR              [        57        23        24
  CONSTINT              2        57        24        25
      CHAR              ]        57        25        26
      CHAR              ;        57        26        27
   ID_TEXT          array        61         2         7
      CHAR              [        61         7         8
  CONSTINT              0        61         8         9
      CHAR              ]        61         9        10
      CHAR              =        61        11        12
      CHAR              (        61        13        14
      CHAR              (        61        14        15
   ID_TEXT              b        61        15        16
      CHAR              +        61        16        17
   ID_TEXT              c        61        17        18
      CHAR              *        61        18        19
   ID_TEXT              e        61        19        20
      CHAR              -        61        20        21
   ID_TEXT              d        61        21        22
      CHAR              -        61        22        23
  CONSTINT              1        61        23        24
      CHAR              )        61        24        25
      CHAR              /        61        25        26
      CHAR              (        61        26        27
      CHAR              (        61        27        28
   ID_TEXT          array        61        28        33
      CHAR              [        61        33        34
  CONSTINT              0        61        34        35
      CHAR              ]        61        35        36
      CHAR              +        61        36        37
      CHAR              (        61        37        38
   ID_TEXT              e        61        38        39
      CHAR              *        61        39        40
   ID_TEXT          array        61        40        45
      CHAR              [        61        45        46
  CONSTINT              3        61        46        47
      CHAR              ]        61        47        48
      CHAR              /        61        48        49
      CHAR              (        61        49        50
   ID_TEXT          array        61        50        55
      CHAR              [        61        55        56
  CONSTINT              2        61        56        57
      CHAR              ]        61        57        58
      CHAR              +        61        58        59
   ID_TEXT          array        61        59        64
      CHAR              [        61        64        65
  CONSTINT              3        61        65        66
      CHAR              ]        61        66        67
      CHAR              )        61        67        68
      CHAR              )        61        68        69
      CHAR              )        61        69        70
      CHAR              )        61        70        71
      CHAR              )        61        71        72
      CHAR              ;        61        72        73
   ID_TEXT         output        65         2         8
      CHAR              (        65         8         9
   ID_TEXT          array        65         9        14
      CHAR              [        65        14        15
  CONSTINT              0        65        15        16
      CHAR              ]        65        16        17
      CHAR              *        65        17        18
   ID_TEXT              b        65        18        19
      CHAR              )        65        19        20
      CHAR              ;        65        20        21
      CHAR              }        66         1         2
