// Generated by Bisonc++ V6.03.00 on Sun, 03 Jan 2021 00:21:22 +0800

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {272, 1}, // 1: Program ->  DeclarationList
     {274, 1}, // 2: ID (ID_TEXT) ->  ID_TEXT
     {275, 1}, // 3: PrimaryExpression (NUM) ->  NUM
     {275, 1}, // 4: PrimaryExpression ->  ID
     {275, 3}, // 5: PrimaryExpression ('(') ->  '(' Expression ')'
     {275, 3}, // 6: PrimaryExpression ('(') ->  '(' errTok_ ')'
     {277, 1}, // 7: PostExpression ->  PrimaryExpression
     {277, 4}, // 8: PostExpression ('(') ->  PostExpression '(' OptArgList ')'
     {277, 4}, // 9: PostExpression ('(') ->  PostExpression '(' errTok_ ')'
     {279, 1}, // 10: PreExpression ->  PostExpression
     {279, 2}, // 11: PreExpression ('-') ->  '-' PreExpression
     {276, 1}, // 12: Expression ->  PreExpression
     {276, 3}, // 13: Expression ('=') ->  Expression '=' Expression
     {276, 3}, // 14: Expression ('<') ->  Expression '<' Expression
     {276, 3}, // 15: Expression ('>') ->  Expression '>' Expression
     {276, 3}, // 16: Expression (LE) ->  Expression LE Expression
     {276, 3}, // 17: Expression (GE) ->  Expression GE Expression
     {276, 3}, // 18: Expression (EQ) ->  Expression EQ Expression
     {276, 3}, // 19: Expression (NE) ->  Expression NE Expression
     {276, 3}, // 20: Expression ('+') ->  Expression '+' Expression
     {276, 3}, // 21: Expression ('-') ->  Expression '-' Expression
     {276, 3}, // 22: Expression ('*') ->  Expression '*' Expression
     {276, 3}, // 23: Expression ('/') ->  Expression '/' Expression
     {280, 1}, // 24: Statement (';') ->  ';'
     {280, 2}, // 25: Statement (errTok_) ->  errTok_ ';'
     {280, 2}, // 26: Statement (';') ->  Expression ';'
     {280, 1}, // 27: Statement ->  Declaration
     {280, 5}, // 28: Statement (IF) ->  IF '(' Expression ')' Statement
     {280, 7}, // 29: Statement (IF) ->  IF '(' Expression ')' Statement ELSE Statement
     {280, 5}, // 30: Statement (WHILE) ->  WHILE '(' Expression ')' Statement
     {280, 2}, // 31: Statement (RETURN) ->  RETURN ';'
     {280, 3}, // 32: Statement (RETURN) ->  RETURN Expression ';'
     {280, 3}, // 33: Statement ('{') ->  '{' StatementList '}'
     {280, 3}, // 34: Statement ('{') ->  '{' errTok_ '}'
     {282, 0}, // 35: StatementList ->  <empty>
     {282, 2}, // 36: StatementList ->  StatementList Statement
     {282, 2}, // 37: StatementList (errTok_) ->  StatementList errTok_
     {278, 0}, // 38: OptArgList ->  <empty>
     {278, 1}, // 39: OptArgList ->  ArgList
     {283, 1}, // 40: ArgList ->  Expression
     {283, 3}, // 41: ArgList (',') ->  ArgList ',' Expression
     {283, 3}, // 42: ArgList (',') ->  ArgList ',' errTok_
     {284, 1}, // 43: VarDecl ->  ID
     {284, 3}, // 44: VarDecl (ARR) ->  VarDecl '[' ']'
     {284, 4}, // 45: VarDecl (ARR) ->  VarDecl '[' Expression ']'
     {284, 4}, // 46: VarDecl (ARR) ->  VarDecl '[' errTok_ ']'
     {284, 2}, // 47: VarDecl (PTR) ->  '*' VarDecl
     {284, 3}, // 48: VarDecl ('(') ->  '(' VarDecl ')'
     {284, 3}, // 49: VarDecl ('(') ->  '(' errTok_ ')'
     {285, 4}, // 50: FuncDecl ('(') ->  ID '(' OptParamList ')'
     {285, 3}, // 51: FuncDecl (ARR) ->  FuncDecl '[' ']'
     {285, 4}, // 52: FuncDecl (ARR) ->  FuncDecl '[' Expression ']'
     {285, 4}, // 53: FuncDecl (ARR) ->  FuncDecl '[' errTok_ ']'
     {285, 2}, // 54: FuncDecl (PTR) ->  '*' FuncDecl
     {285, 3}, // 55: FuncDecl ('(') ->  '(' FuncDecl ')'
     {285, 3}, // 56: FuncDecl ('(') ->  '(' errTok_ ')'
     {287, 0}, // 57: EmptyID ->  <empty>
     {288, 1}, // 58: PureDecl ->  EmptyID
     {288, 4}, // 59: PureDecl ('(') ->  EmptyID '(' OptParamList ')'
     {288, 3}, // 60: PureDecl (ARR) ->  FuncDecl '[' ']'
     {288, 4}, // 61: PureDecl (ARR) ->  FuncDecl '[' Expression ']'
     {288, 4}, // 62: PureDecl (ARR) ->  FuncDecl '[' errTok_ ']'
     {288, 2}, // 63: PureDecl (PTR) ->  '*' FuncDecl
     {288, 3}, // 64: PureDecl ('(') ->  '(' FuncDecl ')'
     {288, 3}, // 65: PureDecl ('(') ->  '(' errTok_ ')'
     {289, 1}, // 66: Decl ->  VarDecl
     {289, 1}, // 67: Decl ->  FuncDecl
     {290, 1}, // 68: InitDecl ->  Decl
     {290, 3}, // 69: InitDecl ('=') ->  Decl '=' Expression
     {291, 1}, // 70: TypePrimitive (VOID) ->  VOID
     {291, 1}, // 71: TypePrimitive (INT) ->  INT
     {291, 2}, // 72: TypePrimitive (STRUCT) ->  STRUCT ID
     {292, 1}, // 73: DeclList ->  InitDecl
     {292, 3}, // 74: DeclList (',') ->  DeclList ',' InitDecl
     {292, 3}, // 75: DeclList (',') ->  DeclList ',' errTok_
     {286, 0}, // 76: OptParamList ->  <empty>
     {286, 1}, // 77: OptParamList (VOID) ->  VOID
     {286, 1}, // 78: OptParamList ->  ParamList
     {293, 2}, // 79: ParamList ->  TypePrimitive Decl
     {293, 4}, // 80: ParamList (',') ->  ParamList ',' TypePrimitive Decl
     {293, 3}, // 81: ParamList (',') ->  ParamList ',' errTok_
     {281, 3}, // 82: Declaration (';') ->  TypePrimitive DeclList ';'
     {281, 5}, // 83: Declaration ('{') ->  TypePrimitive FuncDecl '{' StatementList '}'
     {281, 5}, // 84: Declaration ('{') ->  TypePrimitive FuncDecl '{' errTok_ '}'
     {273, 1}, // 85: DeclarationList ->  Declaration
     {273, 2}, // 86: DeclarationList ->  DeclarationList Declaration
     {273, 2}, // 87: DeclarationList (errTok_) ->  DeclarationList errTok_
     {294, 1}, // 88: Program_$ ->  Program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_TOKEN}, { 8} },                   
    { {       272}, { 1} }, // Program        
    { {       273}, { 2} }, // DeclarationList
    { {       281}, { 3} }, // Declaration    
    { {       291}, { 4} }, // TypePrimitive  
    { {       257}, { 5} }, // VOID           
    { {       258}, { 6} }, // INT            
    { {       263}, { 7} }, // STRUCT         
    { {         0}, { 0} },                   
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       2} }, 
    { {      EOF_}, { ACCEPT_} }, 
    { {         0}, {       0} }, 
};

SR_ s_2[] =
{
    { { ERR_REQ_DEF}, {  7} },                 
    { {         281}, {  8} }, // Declaration  
    { {     errTok_}, {  9} }, // errTok_      
    { {         291}, {  4} }, // TypePrimitive
    { {         257}, {  5} }, // VOID         
    { {         258}, {  6} }, // INT          
    { {         263}, {  7} }, // STRUCT       
    { {           0}, { -1} },                 
};

SR_ s_3[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR_ s_4[] =
{
    { { REQ_TOKEN}, { 10} },            
    { {       292}, { 10} }, // DeclList
    { {       285}, { 11} }, // FuncDecl
    { {       290}, { 12} }, // InitDecl
    { {       274}, { 13} }, // ID      
    { {        42}, { 14} }, // '*'     
    { {        40}, { 15} }, // '('     
    { {       289}, { 16} }, // Decl    
    { {       265}, { 17} }, // ID_TEXT 
    { {       284}, { 18} }, // VarDecl 
    { {         0}, {  0} },            
};

SR_ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR_ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR_ s_7[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       274}, { 19} }, // ID     
    { {       265}, { 17} }, // ID_TEXT
    { {         0}, {  0} },           
};

SR_ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR_ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR_ s_10[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 20} }, // ';'
    { {        44}, { 21} }, // ','
    { {         0}, {  0} },       
};

SR_ s_11[] =
{
    { { REQ_DEF}, {   3} },       
    { {     123}, {  22} }, // '{'
    { {      91}, {  23} }, // '['
    { {       0}, { -67} },       
};

SR_ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR_ s_13[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  24} }, // '('
    { {       0}, { -43} },       
};

SR_ s_14[] =
{
    { { REQ_TOKEN}, {  7} },            
    { {       285}, { 25} }, // FuncDecl
    { {       284}, { 26} }, // VarDecl 
    { {       274}, { 13} }, // ID      
    { {        42}, { 14} }, // '*'     
    { {        40}, { 15} }, // '('     
    { {       265}, { 17} }, // ID_TEXT 
    { {         0}, {  0} },            
};

SR_ s_15[] =
{
    { { ERR_REQ}, {  8} },            
    { {     285}, { 27} }, // FuncDecl
    { { errTok_}, { 28} }, // errTok_ 
    { {     284}, { 29} }, // VarDecl 
    { {     274}, { 13} }, // ID      
    { {      42}, { 14} }, // '*'     
    { {      40}, { 15} }, // '('     
    { {     265}, { 17} }, // ID_TEXT 
    { {       0}, {  0} },            
};

SR_ s_16[] =
{
    { { REQ_DEF}, {   2} },       
    { {      61}, {  30} }, // '='
    { {       0}, { -68} },       
};

SR_ s_17[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR_ s_18[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  31} }, // '['
    { {       0}, { -66} },       
};

SR_ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR_ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR_ s_21[] =
{
    { { ERR_REQ}, { 10} },            
    { {     290}, { 32} }, // InitDecl
    { { errTok_}, { 33} }, // errTok_ 
    { {     289}, { 16} }, // Decl    
    { {     284}, { 18} }, // VarDecl 
    { {     285}, { 34} }, // FuncDecl
    { {     274}, { 13} }, // ID      
    { {      42}, { 14} }, // '*'     
    { {      40}, { 15} }, // '('     
    { {     265}, { 17} }, // ID_TEXT 
    { {       0}, {  0} },            
};

SR_ s_22[] =
{
    { { ERR_REQ_DEF}, {   3} },                 
    { {         282}, {  35} }, // StatementList
    { {     errTok_}, {  36} }, // errTok_      
    { {           0}, { -35} },                 
};

SR_ s_23[] =
{
    { { ERR_REQ}, { 12} },                     
    { {      93}, { 37} }, // ']'              
    { {     276}, { 38} }, // Expression       
    { { errTok_}, { 39} }, // errTok_          
    { {     279}, { 40} }, // PreExpression    
    { {     277}, { 41} }, // PostExpression   
    { {      45}, { 42} }, // '-'              
    { {     275}, { 43} }, // PrimaryExpression
    { {     264}, { 44} }, // NUM              
    { {     274}, { 45} }, // ID               
    { {      40}, { 46} }, // '('              
    { {     265}, { 17} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_24[] =
{
    { { REQ_DEF}, {   7} },                 
    { {     286}, {  47} }, // OptParamList 
    { {     257}, {  48} }, // VOID         
    { {     293}, {  49} }, // ParamList    
    { {     291}, {  50} }, // TypePrimitive
    { {     258}, {   6} }, // INT          
    { {     263}, {   7} }, // STRUCT       
    { {       0}, { -76} },                 
};

SR_ s_25[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -54} }, 
};

SR_ s_26[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -47} }, 
};

SR_ s_27[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 51} }, // ')'
    { {        91}, { 23} }, // '['
    { {         0}, {  0} },       
};

SR_ s_28[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 52} }, // ')'
    { {         0}, {  0} },       
};

SR_ s_29[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 53} }, // ')'
    { {        91}, { 31} }, // '['
    { {         0}, {  0} },       
};

SR_ s_30[] =
{
    { { REQ_TOKEN}, { 10} },                     
    { {       276}, { 54} }, // Expression       
    { {       279}, { 40} }, // PreExpression    
    { {       277}, { 41} }, // PostExpression   
    { {        45}, { 42} }, // '-'              
    { {       275}, { 43} }, // PrimaryExpression
    { {       264}, { 44} }, // NUM              
    { {       274}, { 45} }, // ID               
    { {        40}, { 46} }, // '('              
    { {       265}, { 17} }, // ID_TEXT          
    { {         0}, {  0} },                     
};

SR_ s_31[] =
{
    { { ERR_REQ}, { 12} },                     
    { {      93}, { 55} }, // ']'              
    { {     276}, { 56} }, // Expression       
    { { errTok_}, { 57} }, // errTok_          
    { {     279}, { 40} }, // PreExpression    
    { {     277}, { 41} }, // PostExpression   
    { {      45}, { 42} }, // '-'              
    { {     275}, { 43} }, // PrimaryExpression
    { {     264}, { 44} }, // NUM              
    { {     274}, { 45} }, // ID               
    { {      40}, { 46} }, // '('              
    { {     265}, { 17} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR_ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR_ s_34[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  23} }, // '['
    { {       0}, { -67} },       
};

SR_ s_35[] =
{
    { { ERR_REQ}, { 23} },                     
    { {     125}, { 58} }, // '}'              
    { {     280}, { 59} }, // Statement        
    { { errTok_}, { 60} }, // errTok_          
    { {      59}, { 61} }, // ';'              
    { {     276}, { 62} }, // Expression       
    { {     281}, { 63} }, // Declaration      
    { {     260}, { 64} }, // IF               
    { {     262}, { 65} }, // WHILE            
    { {     259}, { 66} }, // RETURN           
    { {     123}, { 67} }, // '{'              
    { {     279}, { 40} }, // PreExpression    
    { {     291}, {  4} }, // TypePrimitive    
    { {     277}, { 41} }, // PostExpression   
    { {      45}, { 42} }, // '-'              
    { {     257}, {  5} }, // VOID             
    { {     258}, {  6} }, // INT              
    { {     263}, {  7} }, // STRUCT           
    { {     275}, { 43} }, // PrimaryExpression
    { {     264}, { 44} }, // NUM              
    { {     274}, { 45} }, // ID               
    { {      40}, { 46} }, // '('              
    { {     265}, { 17} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_36[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 68} }, // '}'
    { {         0}, {  0} },       
};

SR_ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR_ s_38[] =
{
    { { REQ_TOKEN}, { 13} },       
    { {        93}, { 69} }, // ']'
    { {        61}, { 70} }, // '='
    { {        60}, { 71} }, // '<'
    { {        62}, { 72} }, // '>'
    { {       268}, { 73} }, // LE 
    { {       269}, { 74} }, // GE 
    { {       270}, { 75} }, // EQ 
    { {       271}, { 76} }, // NE 
    { {        43}, { 77} }, // '+'
    { {        45}, { 78} }, // '-'
    { {        42}, { 79} }, // '*'
    { {        47}, { 80} }, // '/'
    { {         0}, {  0} },       
};

SR_ s_39[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        93}, { 81} }, // ']'
    { {         0}, {  0} },       
};

SR_ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR_ s_41[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  82} }, // '('
    { {       0}, { -10} },       
};

SR_ s_42[] =
{
    { { REQ_TOKEN}, {  9} },                     
    { {       279}, { 83} }, // PreExpression    
    { {       277}, { 41} }, // PostExpression   
    { {        45}, { 42} }, // '-'              
    { {       275}, { 43} }, // PrimaryExpression
    { {       264}, { 44} }, // NUM              
    { {       274}, { 45} }, // ID               
    { {        40}, { 46} }, // '('              
    { {       265}, { 17} }, // ID_TEXT          
    { {         0}, {  0} },                     
};

SR_ s_43[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_44[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_45[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR_ s_46[] =
{
    { { ERR_REQ}, { 11} },                     
    { {     276}, { 84} }, // Expression       
    { { errTok_}, { 85} }, // errTok_          
    { {     279}, { 40} }, // PreExpression    
    { {     277}, { 41} }, // PostExpression   
    { {      45}, { 42} }, // '-'              
    { {     275}, { 43} }, // PrimaryExpression
    { {     264}, { 44} }, // NUM              
    { {     274}, { 45} }, // ID               
    { {      40}, { 46} }, // '('              
    { {     265}, { 17} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_47[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 86} }, // ')'
    { {         0}, {  0} },       
};

SR_ s_48[] =
{
    { { REQ_DEF}, {   2} },       
    { {      41}, { -77} }, // ')'
    { {       0}, { -70} },       
};

SR_ s_49[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  87} }, // ','
    { {       0}, { -78} },       
};

SR_ s_50[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       289}, { 88} }, // Decl    
    { {       284}, { 18} }, // VarDecl 
    { {       285}, { 34} }, // FuncDecl
    { {       274}, { 13} }, // ID      
    { {        42}, { 14} }, // '*'     
    { {        40}, { 15} }, // '('     
    { {       265}, { 17} }, // ID_TEXT 
    { {         0}, {  0} },            
};

SR_ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR_ s_52[] =
{
    { { REQ_DEF}, {   2} },       
    { {     123}, { -56} }, // '{'
    { {       0}, { -49} },       
};

SR_ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR_ s_54[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  70} }, // '='
    { {      60}, {  71} }, // '<'
    { {      62}, {  72} }, // '>'
    { {     268}, {  73} }, // LE 
    { {     269}, {  74} }, // GE 
    { {     270}, {  75} }, // EQ 
    { {     271}, {  76} }, // NE 
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -69} },       
};

SR_ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR_ s_56[] =
{
    { { REQ_TOKEN}, { 13} },       
    { {        93}, { 89} }, // ']'
    { {        61}, { 70} }, // '='
    { {        60}, { 71} }, // '<'
    { {        62}, { 72} }, // '>'
    { {       268}, { 73} }, // LE 
    { {       269}, { 74} }, // GE 
    { {       270}, { 75} }, // EQ 
    { {       271}, { 76} }, // NE 
    { {        43}, { 77} }, // '+'
    { {        45}, { 78} }, // '-'
    { {        42}, { 79} }, // '*'
    { {        47}, { 80} }, // '/'
    { {         0}, {  0} },       
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        93}, { 90} }, // ']'
    { {         0}, {  0} },       
};

SR_ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR_ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR_ s_60[] =
{
    { { REQ_DEF}, {   2} },       
    { {      59}, {  91} }, // ';'
    { {       0}, { -37} },       
};

SR_ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR_ s_62[] =
{
    { { REQ_TOKEN}, { 13} },       
    { {        59}, { 92} }, // ';'
    { {        61}, { 70} }, // '='
    { {        60}, { 71} }, // '<'
    { {        62}, { 72} }, // '>'
    { {       268}, { 73} }, // LE 
    { {       269}, { 74} }, // GE 
    { {       270}, { 75} }, // EQ 
    { {       271}, { 76} }, // NE 
    { {        43}, { 77} }, // '+'
    { {        45}, { 78} }, // '-'
    { {        42}, { 79} }, // '*'
    { {        47}, { 80} }, // '/'
    { {         0}, {  0} },       
};

SR_ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR_ s_64[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 93} }, // '('
    { {         0}, {  0} },       
};

SR_ s_65[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 94} }, // '('
    { {         0}, {  0} },       
};

SR_ s_66[] =
{
    { { REQ_TOKEN}, { 11} },                     
    { {        59}, { 95} }, // ';'              
    { {       276}, { 96} }, // Expression       
    { {       279}, { 40} }, // PreExpression    
    { {       277}, { 41} }, // PostExpression   
    { {        45}, { 42} }, // '-'              
    { {       275}, { 43} }, // PrimaryExpression
    { {       264}, { 44} }, // NUM              
    { {       274}, { 45} }, // ID               
    { {        40}, { 46} }, // '('              
    { {       265}, { 17} }, // ID_TEXT          
    { {         0}, {  0} },                     
};

SR_ s_67[] =
{
    { { ERR_REQ_DEF}, {   3} },                 
    { {         282}, {  97} }, // StatementList
    { {     errTok_}, {  98} }, // errTok_      
    { {           0}, { -35} },                 
};

SR_ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR_ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR_ s_70[] =
{
    { { REQ_TOKEN}, { 10} },                     
    { {       276}, { 99} }, // Expression       
    { {       279}, { 40} }, // PreExpression    
    { {       277}, { 41} }, // PostExpression   
    { {        45}, { 42} }, // '-'              
    { {       275}, { 43} }, // PrimaryExpression
    { {       264}, { 44} }, // NUM              
    { {       274}, { 45} }, // ID               
    { {        40}, { 46} }, // '('              
    { {       265}, { 17} }, // ID_TEXT          
    { {         0}, {  0} },                     
};

SR_ s_71[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 100} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_72[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 101} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_73[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 102} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_74[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 103} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_75[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 104} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_76[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 105} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_77[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 106} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_78[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 107} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 108} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_80[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 109} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR_ s_82[] =
{
    { { ERR_REQ_DEF}, {  13} },                     
    { {         278}, { 110} }, // OptArgList       
    { {     errTok_}, { 111} }, // errTok_          
    { {         283}, { 112} }, // ArgList          
    { {         276}, { 113} }, // Expression       
    { {         279}, {  40} }, // PreExpression    
    { {         277}, {  41} }, // PostExpression   
    { {          45}, {  42} }, // '-'              
    { {         275}, {  43} }, // PrimaryExpression
    { {         264}, {  44} }, // NUM              
    { {         274}, {  45} }, // ID               
    { {          40}, {  46} }, // '('              
    { {         265}, {  17} }, // ID_TEXT          
    { {           0}, { -38} },                     
};

SR_ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_84[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 114} }, // ')'
    { {        61}, {  70} }, // '='
    { {        60}, {  71} }, // '<'
    { {        62}, {  72} }, // '>'
    { {       268}, {  73} }, // LE 
    { {       269}, {  74} }, // GE 
    { {       270}, {  75} }, // EQ 
    { {       271}, {  76} }, // NE 
    { {        43}, {  77} }, // '+'
    { {        45}, {  78} }, // '-'
    { {        42}, {  79} }, // '*'
    { {        47}, {  80} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_85[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 115} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR_ s_87[] =
{
    { { ERR_REQ}, {   6} },                 
    { {     291}, { 116} }, // TypePrimitive
    { { errTok_}, { 117} }, // errTok_      
    { {     257}, {   5} }, // VOID         
    { {     258}, {   6} }, // INT          
    { {     263}, {   7} }, // STRUCT       
    { {       0}, {   0} },                 
};

SR_ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR_ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR_ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR_ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR_ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR_ s_93[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 118} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_94[] =
{
    { { REQ_TOKEN}, {  10} },                     
    { {       276}, { 119} }, // Expression       
    { {       279}, {  40} }, // PreExpression    
    { {       277}, {  41} }, // PostExpression   
    { {        45}, {  42} }, // '-'              
    { {       275}, {  43} }, // PrimaryExpression
    { {       264}, {  44} }, // NUM              
    { {       274}, {  45} }, // ID               
    { {        40}, {  46} }, // '('              
    { {       265}, {  17} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR_ s_96[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        59}, { 120} }, // ';'
    { {        61}, {  70} }, // '='
    { {        60}, {  71} }, // '<'
    { {        62}, {  72} }, // '>'
    { {       268}, {  73} }, // LE 
    { {       269}, {  74} }, // GE 
    { {       270}, {  75} }, // EQ 
    { {       271}, {  76} }, // NE 
    { {        43}, {  77} }, // '+'
    { {        45}, {  78} }, // '-'
    { {        42}, {  79} }, // '*'
    { {        47}, {  80} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_97[] =
{
    { { ERR_REQ}, {  23} },                     
    { {     125}, { 121} }, // '}'              
    { {     280}, {  59} }, // Statement        
    { { errTok_}, {  60} }, // errTok_          
    { {      59}, {  61} }, // ';'              
    { {     276}, {  62} }, // Expression       
    { {     281}, {  63} }, // Declaration      
    { {     260}, {  64} }, // IF               
    { {     262}, {  65} }, // WHILE            
    { {     259}, {  66} }, // RETURN           
    { {     123}, {  67} }, // '{'              
    { {     279}, {  40} }, // PreExpression    
    { {     291}, {   4} }, // TypePrimitive    
    { {     277}, {  41} }, // PostExpression   
    { {      45}, {  42} }, // '-'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // INT              
    { {     263}, {   7} }, // STRUCT           
    { {     275}, {  43} }, // PrimaryExpression
    { {     264}, {  44} }, // NUM              
    { {     274}, {  45} }, // ID               
    { {      40}, {  46} }, // '('              
    { {     265}, {  17} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_98[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 122} }, // '}'
    { {         0}, {   0} },       
};

SR_ s_99[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  70} }, // '='
    { {      60}, {  71} }, // '<'
    { {      62}, {  72} }, // '>'
    { {     268}, {  73} }, // LE 
    { {     269}, {  74} }, // GE 
    { {     270}, {  75} }, // EQ 
    { {     271}, {  76} }, // NE 
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -13} },       
};

SR_ s_100[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -14} },       
};

SR_ s_101[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -15} },       
};

SR_ s_102[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -16} },       
};

SR_ s_103[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -17} },       
};

SR_ s_104[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -18} },       
};

SR_ s_105[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -19} },       
};

SR_ s_106[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -20} },       
};

SR_ s_107[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -21} },       
};

SR_ s_108[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -22} }, 
};

SR_ s_109[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -23} }, 
};

SR_ s_110[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 123} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_111[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 124} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_112[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 125} }, // ','
    { {       0}, { -39} },       
};

SR_ s_113[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  70} }, // '='
    { {      60}, {  71} }, // '<'
    { {      62}, {  72} }, // '>'
    { {     268}, {  73} }, // LE 
    { {     269}, {  74} }, // GE 
    { {     270}, {  75} }, // EQ 
    { {     271}, {  76} }, // NE 
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -40} },       
};

SR_ s_114[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_115[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR_ s_116[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       289}, { 126} }, // Decl    
    { {       284}, {  18} }, // VarDecl 
    { {       285}, {  34} }, // FuncDecl
    { {       274}, {  13} }, // ID      
    { {        42}, {  14} }, // '*'     
    { {        40}, {  15} }, // '('     
    { {       265}, {  17} }, // ID_TEXT 
    { {         0}, {   0} },            
};

SR_ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR_ s_118[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 127} }, // ')'
    { {        61}, {  70} }, // '='
    { {        60}, {  71} }, // '<'
    { {        62}, {  72} }, // '>'
    { {       268}, {  73} }, // LE 
    { {       269}, {  74} }, // GE 
    { {       270}, {  75} }, // EQ 
    { {       271}, {  76} }, // NE 
    { {        43}, {  77} }, // '+'
    { {        45}, {  78} }, // '-'
    { {        42}, {  79} }, // '*'
    { {        47}, {  80} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_119[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 128} }, // ')'
    { {        61}, {  70} }, // '='
    { {        60}, {  71} }, // '<'
    { {        62}, {  72} }, // '>'
    { {       268}, {  73} }, // LE 
    { {       269}, {  74} }, // GE 
    { {       270}, {  75} }, // EQ 
    { {       271}, {  76} }, // NE 
    { {        43}, {  77} }, // '+'
    { {        45}, {  78} }, // '-'
    { {        42}, {  79} }, // '*'
    { {        47}, {  80} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_120[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR_ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR_ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR_ s_123[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_124[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR_ s_125[] =
{
    { { ERR_REQ}, {  11} },                     
    { {     276}, { 129} }, // Expression       
    { { errTok_}, { 130} }, // errTok_          
    { {     279}, {  40} }, // PreExpression    
    { {     277}, {  41} }, // PostExpression   
    { {      45}, {  42} }, // '-'              
    { {     275}, {  43} }, // PrimaryExpression
    { {     264}, {  44} }, // NUM              
    { {     274}, {  45} }, // ID               
    { {      40}, {  46} }, // '('              
    { {     265}, {  17} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR_ s_127[] =
{
    { { ERR_REQ}, {  22} },                     
    { {     280}, { 131} }, // Statement        
    { {      59}, {  61} }, // ';'              
    { { errTok_}, { 132} }, // errTok_          
    { {     276}, {  62} }, // Expression       
    { {     281}, {  63} }, // Declaration      
    { {     260}, {  64} }, // IF               
    { {     262}, {  65} }, // WHILE            
    { {     259}, {  66} }, // RETURN           
    { {     123}, {  67} }, // '{'              
    { {     279}, {  40} }, // PreExpression    
    { {     291}, {   4} }, // TypePrimitive    
    { {     277}, {  41} }, // PostExpression   
    { {      45}, {  42} }, // '-'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // INT              
    { {     263}, {   7} }, // STRUCT           
    { {     275}, {  43} }, // PrimaryExpression
    { {     264}, {  44} }, // NUM              
    { {     274}, {  45} }, // ID               
    { {      40}, {  46} }, // '('              
    { {     265}, {  17} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_128[] =
{
    { { ERR_REQ}, {  22} },                     
    { {     280}, { 133} }, // Statement        
    { {      59}, {  61} }, // ';'              
    { { errTok_}, { 132} }, // errTok_          
    { {     276}, {  62} }, // Expression       
    { {     281}, {  63} }, // Declaration      
    { {     260}, {  64} }, // IF               
    { {     262}, {  65} }, // WHILE            
    { {     259}, {  66} }, // RETURN           
    { {     123}, {  67} }, // '{'              
    { {     279}, {  40} }, // PreExpression    
    { {     291}, {   4} }, // TypePrimitive    
    { {     277}, {  41} }, // PostExpression   
    { {      45}, {  42} }, // '-'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // INT              
    { {     263}, {   7} }, // STRUCT           
    { {     275}, {  43} }, // PrimaryExpression
    { {     264}, {  44} }, // NUM              
    { {     274}, {  45} }, // ID               
    { {      40}, {  46} }, // '('              
    { {     265}, {  17} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_129[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  70} }, // '='
    { {      60}, {  71} }, // '<'
    { {      62}, {  72} }, // '>'
    { {     268}, {  73} }, // LE 
    { {     269}, {  74} }, // GE 
    { {     270}, {  75} }, // EQ 
    { {     271}, {  76} }, // NE 
    { {      43}, {  77} }, // '+'
    { {      45}, {  78} }, // '-'
    { {      42}, {  79} }, // '*'
    { {      47}, {  80} }, // '/'
    { {       0}, { -41} },       
};

SR_ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR_ s_131[] =
{
    { { REQ_DEF}, {   2} },        
    { {     261}, { 134} }, // ELSE
    { {       0}, { -28} },        
};

SR_ s_132[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 91} }, // ';'
    { {         0}, {  0} },       
};

SR_ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR_ s_134[] =
{
    { { ERR_REQ}, {  22} },                     
    { {     280}, { 135} }, // Statement        
    { {      59}, {  61} }, // ';'              
    { { errTok_}, { 132} }, // errTok_          
    { {     276}, {  62} }, // Expression       
    { {     281}, {  63} }, // Declaration      
    { {     260}, {  64} }, // IF               
    { {     262}, {  65} }, // WHILE            
    { {     259}, {  66} }, // RETURN           
    { {     123}, {  67} }, // '{'              
    { {     279}, {  40} }, // PreExpression    
    { {     291}, {   4} }, // TypePrimitive    
    { {     277}, {  41} }, // PostExpression   
    { {      45}, {  42} }, // '-'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // INT              
    { {     263}, {   7} }, // STRUCT           
    { {     275}, {  43} }, // PrimaryExpression
    { {     264}, {  44} }, // NUM              
    { {     274}, {  45} }, // ID               
    { {      40}, {  46} }, // '('              
    { {     265}, {  17} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void ParserBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void ParserBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void ParserBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = std::move(d_next.second);

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void ParserBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void ParserBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Parser::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
        { _Root = std::move(vs_(0)); }
        break;

        case 2:
        { d_val_ = std::make_unique<ast::ID>(_Scanner->matched(), _Scanner->GetLocation()); }
        break;

        case 3:
        { d_val_ = std::make_unique<ast::Constant>(std::stod(_Scanner->matched())); }
        break;

        case 4:
        { d_val_ = std::make_unique<ast::Variable>(vs_(0)); }
        break;

        case 5:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 6:
        { d_val_ = nullptr; }
        break;

        case 7:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 8:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::CallExpr>(d_val_)->SetFunc(vs_(-3)); }
        break;

        case 9:
        { d_val_ = nullptr; }
        break;

        case 10:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 11:
        { d_val_ = std::make_unique<ast::UnOpExpr>(vs_(0), ast::UnOpExpr::NEG); }
        break;

        case 12:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 13:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::ASSIGN); }
        break;

        case 14:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::LESS); }
        break;

        case 15:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::GREATER); }
        break;

        case 16:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::LESS_EQUAL); }
        break;

        case 17:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::GREATER_EQUAL); }
        break;

        case 18:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::EQUAL); }
        break;

        case 19:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::NOT_EQUAL); }
        break;

        case 20:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::ADD); }
        break;

        case 21:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::SUB); }
        break;

        case 22:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::MUL); }
        break;

        case 23:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::DIV); }
        break;

        case 24:
        { d_val_ = std::make_unique<ast::ExprStmt>(); }
        break;

        case 25:
        { d_val_ = nullptr; }
        break;

        case 26:
        { d_val_ = std::make_unique<ast::ExprStmt>(vs_(-1)); }
        break;

        case 27:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 28:
        { d_val_ = std::make_unique<ast::IfStmt>(vs_(-2), vs_(0)); }
        break;

        case 29:
        { d_val_ = std::make_unique<ast::IfStmt>(vs_(-4), vs_(-2), vs_(0)); }
        break;

        case 30:
        { d_val_ = std::make_unique<ast::WhileStmt>(vs_(-2), vs_(0)); }
        break;

        case 31:
        { d_val_ = std::make_unique<ast::ReturnStmt>(); }
        break;

        case 32:
        { d_val_ = std::make_unique<ast::ReturnStmt>(vs_(-1)); }
        break;

        case 33:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 34:
        { d_val_ = nullptr; }
        break;

        case 35:
        { d_val_ = std::make_unique<ast::StatementList>(); }
        break;

        case 36:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::StatementList>(d_val_)->AddStmt(vs_(0)); }
        break;

        case 37:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 38:
        { d_val_ = std::make_unique<ast::CallExpr>(); }
        break;

        case 39:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 40:
        { d_val_ = std::make_unique<ast::CallExpr>(vs_(0)); }
        break;

        case 41:
        { d_val_ = std::move(vs_(-2)); ast::cast<ast::CallExpr>(d_val_)->AddArg(vs_(0)); }
        break;

        case 42:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 43:
        { d_val_ = std::make_unique<ast::VarDecl>(vs_(0)); }
        break;

        case 44:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-2)); }
        break;

        case 45:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-3), vs_(-1)); }
        break;

        case 46:
        { d_val_ = nullptr; }
        break;

        case 47:
        { d_val_ = std::make_unique<ast::PointerDecl>(vs_(0)); }
        break;

        case 48:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 49:
        { d_val_ = nullptr; }
        break;

        case 50:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::FuncDecl>(d_val_)->SetName(vs_(-3)); }
        break;

        case 51:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-2)); }
        break;

        case 52:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-3), vs_(-1)); }
        break;

        case 53:
        { d_val_ = nullptr; }
        break;

        case 54:
        { d_val_ = std::make_unique<ast::PointerDecl>(vs_(0)); }
        break;

        case 55:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 56:
        { d_val_ = nullptr; }
        break;

        case 57:
        { d_val_ = std::make_unique<ast::ID>("", _Scanner->GetLocation()); }
        break;

        case 58:
        { d_val_ = std::make_unique<ast::VarDecl>(vs_(0)); }
        break;

        case 59:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::FuncDecl>(d_val_)->SetName(vs_(-3)); }
        break;

        case 60:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-2)); }
        break;

        case 61:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-3), vs_(-1)); }
        break;

        case 62:
        { d_val_ = nullptr; }
        break;

        case 63:
        { d_val_ = std::make_unique<ast::PointerDecl>(vs_(0)); }
        break;

        case 64:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 65:
        { d_val_ = nullptr; }
        break;

        case 66:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 67:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 68:
        { d_val_ = std::make_unique<ast::InitDecl>(vs_(0)); }
        break;

        case 69:
        { d_val_ = std::make_unique<ast::InitDecl>(vs_(-2), vs_(0)); }
        break;

        case 70:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::VOID); }
        break;

        case 71:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::INT); }
        break;

        case 72:
        { d_val_ = std::make_unique<ast::CustomType>(vs_(0)); }
        break;

        case 73:
        { d_val_ = std::make_unique<ast::VarDeclaration>(vs_(0)); }
        break;

        case 74:
        { d_val_ = std::move(vs_(-2)); ast::cast<ast::VarDeclaration>(d_val_)->AddVar(vs_(0)); }
        break;

        case 75:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 76:
        { d_val_ = std::make_unique<ast::FuncDecl>(); }
        break;

        case 77:
        { d_val_ = std::make_unique<ast::FuncDecl>(); }
        break;

        case 78:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 79:
        { d_val_ = std::make_unique<ast::FuncDecl>(vs_(-1), vs_(0)); }
        break;

        case 80:
        { d_val_ = std::move(vs_(-3)); ast::cast<ast::FuncDecl>(d_val_)->AddParam(vs_(-1), vs_(0)); }
        break;

        case 81:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 82:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::VarDeclaration>(d_val_)->SetType(vs_(-2)); }
        break;

        case 83:
        { d_val_ = std::make_unique<ast::FuncDeclaration>(vs_(-4), vs_(-3), vs_(-1)); }
        break;

        case 84:
        { d_val_ = nullptr; }
        break;

        case 85:
        { d_val_ = std::make_unique<ast::DeclarationList>(vs_(0)); }
        break;

        case 86:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::DeclarationList>(d_val_)->AddDecl(vs_(0)); }
        break;

        case 87:
        { d_val_ = std::move(vs_(-1)); }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Parser::print_()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


// This function will be appended to parse.cc

std::vector<int> Parser::ValidTokens()
{
    auto sr = s_state[state_()];
    auto last = sr + sr->d_lastIdx;
    std::set<int> set;
    std::vector<int> res;
    for (; ++sr != last;)
        if (sr->d_token > 0 && sr->d_token != 256 && 
            sr->d_token < 257 + static_cast<int>(TOKEN_COUNT) &&
            set.find(sr->d_token) == set.end())
        {
            set.insert(sr->d_token);
            res.push_back(sr->d_token);
        }
    if (sr == last && sr->d_action < 0)
        if (sr->d_token > 0 && sr->d_token != 256 && 
            sr->d_token < 257 + static_cast<int>(TOKEN_COUNT) &&
            set.find(sr->d_token) == set.end())
        {
            set.insert(sr->d_token);
            res.push_back(sr->d_token);
        }
    return res;
}
