// Generated by Bisonc++ V6.03.00 on Mon, 04 Jan 2021 04:43:52 +0800

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {282, 1}, // 1: Program ->  DeclarationList
     {284, 1}, // 2: ID (ID_TEXT) ->  ID_TEXT
     {285, 1}, // 3: PrimaryExpression (TRUE) ->  TRUE
     {285, 1}, // 4: PrimaryExpression (FALSE) ->  FALSE
     {285, 1}, // 5: PrimaryExpression (CONSTINT) ->  CONSTINT
     {285, 1}, // 6: PrimaryExpression (CONSTINT_BIN) ->  CONSTINT_BIN
     {285, 1}, // 7: PrimaryExpression (CONSTINT_OCT) ->  CONSTINT_OCT
     {285, 1}, // 8: PrimaryExpression (CONSTINT_HEX) ->  CONSTINT_HEX
     {285, 1}, // 9: PrimaryExpression (CONSTFP) ->  CONSTFP
     {285, 1}, // 10: PrimaryExpression ->  ID
     {285, 3}, // 11: PrimaryExpression ('(') ->  '(' Expression ')'
     {285, 3}, // 12: PrimaryExpression ('(') ->  '(' errTok_ ')'
     {287, 1}, // 13: PostExpression ->  PrimaryExpression
     {287, 4}, // 14: PostExpression ('(') ->  PostExpression '(' OptArgList ')'
     {287, 4}, // 15: PostExpression ('(') ->  PostExpression '(' errTok_ ')'
     {289, 1}, // 16: PreExpression ->  PostExpression
     {289, 2}, // 17: PreExpression ('+') ->  '+' PreExpression
     {289, 2}, // 18: PreExpression ('-') ->  '-' PreExpression
     {289, 2}, // 19: PreExpression ('*') ->  '*' PreExpression
     {289, 2}, // 20: PreExpression ('&') ->  '&' PreExpression
     {286, 1}, // 21: Expression ->  PreExpression
     {286, 3}, // 22: Expression ('=') ->  Expression '=' Expression
     {286, 3}, // 23: Expression ('<') ->  Expression '<' Expression
     {286, 3}, // 24: Expression ('>') ->  Expression '>' Expression
     {286, 3}, // 25: Expression (LE) ->  Expression LE Expression
     {286, 3}, // 26: Expression (GE) ->  Expression GE Expression
     {286, 3}, // 27: Expression (EQ) ->  Expression EQ Expression
     {286, 3}, // 28: Expression (NE) ->  Expression NE Expression
     {286, 3}, // 29: Expression ('+') ->  Expression '+' Expression
     {286, 3}, // 30: Expression ('-') ->  Expression '-' Expression
     {286, 3}, // 31: Expression ('*') ->  Expression '*' Expression
     {286, 3}, // 32: Expression ('/') ->  Expression '/' Expression
     {290, 1}, // 33: Statement (';') ->  ';'
     {290, 2}, // 34: Statement (errTok_) ->  errTok_ ';'
     {290, 2}, // 35: Statement (';') ->  Expression ';'
     {290, 1}, // 36: Statement ->  Declaration
     {290, 5}, // 37: Statement (IF) ->  IF '(' Expression ')' Statement
     {290, 7}, // 38: Statement (IF) ->  IF '(' Expression ')' Statement ELSE Statement
     {290, 5}, // 39: Statement (WHILE) ->  WHILE '(' Expression ')' Statement
     {290, 2}, // 40: Statement (RETURN) ->  RETURN ';'
     {290, 3}, // 41: Statement (RETURN) ->  RETURN Expression ';'
     {290, 3}, // 42: Statement ('{') ->  '{' StatementList '}'
     {290, 3}, // 43: Statement ('{') ->  '{' errTok_ '}'
     {292, 0}, // 44: StatementList ->  <empty>
     {292, 2}, // 45: StatementList ->  StatementList Statement
     {292, 2}, // 46: StatementList (errTok_) ->  StatementList errTok_
     {288, 0}, // 47: OptArgList ->  <empty>
     {288, 1}, // 48: OptArgList ->  ArgList
     {293, 1}, // 49: ArgList ->  Expression
     {293, 3}, // 50: ArgList (',') ->  ArgList ',' Expression
     {293, 3}, // 51: ArgList (',') ->  ArgList ',' errTok_
     {294, 1}, // 52: PrimaryVarDecl ->  ID
     {294, 3}, // 53: PrimaryVarDecl ('(') ->  '(' VarDecl ')'
     {294, 3}, // 54: PrimaryVarDecl ('(') ->  '(' errTok_ ')'
     {296, 1}, // 55: PostVarDecl ->  PrimaryVarDecl
     {296, 3}, // 56: PostVarDecl ('[') ->  PostVarDecl '[' ']'
     {296, 4}, // 57: PostVarDecl ('[') ->  PostVarDecl '[' Expression ']'
     {296, 4}, // 58: PostVarDecl ('[') ->  PostVarDecl '[' errTok_ ']'
     {295, 1}, // 59: VarDecl ->  PostVarDecl
     {295, 2}, // 60: VarDecl ('*') ->  '*' VarDecl
     {295, 2}, // 61: VarDecl ('&') ->  '&' VarDecl
     {297, 4}, // 62: PrimaryFuncDecl ('(') ->  ID '(' OptParamList ')'
     {297, 3}, // 63: PrimaryFuncDecl ('(') ->  '(' FuncDecl ')'
     {297, 3}, // 64: PrimaryFuncDecl ('(') ->  '(' errTok_ ')'
     {300, 1}, // 65: PostFuncDecl ->  PrimaryFuncDecl
     {300, 3}, // 66: PostFuncDecl ('[') ->  PostFuncDecl '[' ']'
     {300, 4}, // 67: PostFuncDecl ('[') ->  PostFuncDecl '[' Expression ']'
     {300, 4}, // 68: PostFuncDecl ('[') ->  PostFuncDecl '[' errTok_ ']'
     {299, 1}, // 69: FuncDecl ->  PostFuncDecl
     {299, 2}, // 70: FuncDecl ('*') ->  '*' FuncDecl
     {299, 2}, // 71: FuncDecl ('&') ->  '&' FuncDecl
     {301, 1}, // 72: Decl ->  VarDecl
     {301, 1}, // 73: Decl ->  FuncDecl
     {302, 1}, // 74: InitDecl ->  Decl
     {302, 3}, // 75: InitDecl ('=') ->  Decl '=' Expression
     {303, 1}, // 76: TypePrimitive (VOID) ->  VOID
     {303, 1}, // 77: TypePrimitive (BOOL) ->  BOOL
     {303, 1}, // 78: TypePrimitive (CHAR) ->  CHAR
     {303, 1}, // 79: TypePrimitive (SHORT) ->  SHORT
     {303, 1}, // 80: TypePrimitive (INT) ->  INT
     {303, 1}, // 81: TypePrimitive (LONG) ->  LONG
     {303, 1}, // 82: TypePrimitive (FLOAT) ->  FLOAT
     {303, 1}, // 83: TypePrimitive (DOUBLE) ->  DOUBLE
     {303, 2}, // 84: TypePrimitive (STRUCT) ->  STRUCT ID
     {304, 1}, // 85: DeclList ->  InitDecl
     {304, 3}, // 86: DeclList (',') ->  DeclList ',' InitDecl
     {304, 3}, // 87: DeclList (',') ->  DeclList ',' errTok_
     {298, 0}, // 88: OptParamList ->  <empty>
     {298, 1}, // 89: OptParamList (VOID) ->  VOID
     {298, 1}, // 90: OptParamList ->  ParamList
     {305, 2}, // 91: ParamList ->  TypePrimitive Decl
     {305, 4}, // 92: ParamList (',') ->  ParamList ',' TypePrimitive Decl
     {305, 3}, // 93: ParamList (',') ->  ParamList ',' errTok_
     {291, 3}, // 94: Declaration (';') ->  TypePrimitive DeclList ';'
     {291, 5}, // 95: Declaration ('{') ->  TypePrimitive FuncDecl '{' StatementList '}'
     {291, 5}, // 96: Declaration ('{') ->  TypePrimitive FuncDecl '{' errTok_ '}'
     {283, 1}, // 97: DeclarationList ->  Declaration
     {283, 2}, // 98: DeclarationList ->  DeclarationList Declaration
     {283, 2}, // 99: DeclarationList (errTok_) ->  DeclarationList errTok_
     {306, 1}, // 100: Program_$ ->  Program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_TOKEN}, { 14} },                   
    { {       282}, {  1} }, // Program        
    { {       283}, {  2} }, // DeclarationList
    { {       291}, {  3} }, // Declaration    
    { {       303}, {  4} }, // TypePrimitive  
    { {       257}, {  5} }, // VOID           
    { {       258}, {  6} }, // BOOL           
    { {       259}, {  7} }, // CHAR           
    { {       260}, {  8} }, // SHORT          
    { {       261}, {  9} }, // INT            
    { {       262}, { 10} }, // LONG           
    { {       263}, { 11} }, // FLOAT          
    { {       264}, { 12} }, // DOUBLE         
    { {       271}, { 13} }, // STRUCT         
    { {         0}, {  0} },                   
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       2} }, 
    { {      EOF_}, { ACCEPT_} }, 
    { {         0}, {       0} }, 
};

SR_ s_2[] =
{
    { { ERR_REQ_DEF}, { 13} },                 
    { {         291}, { 14} }, // Declaration  
    { {     errTok_}, { 15} }, // errTok_      
    { {         303}, {  4} }, // TypePrimitive
    { {         257}, {  5} }, // VOID         
    { {         258}, {  6} }, // BOOL         
    { {         259}, {  7} }, // CHAR         
    { {         260}, {  8} }, // SHORT        
    { {         261}, {  9} }, // INT          
    { {         262}, { 10} }, // LONG         
    { {         263}, { 11} }, // FLOAT        
    { {         264}, { 12} }, // DOUBLE       
    { {         271}, { 13} }, // STRUCT       
    { {           0}, { -1} },                 
};

SR_ s_3[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -97} }, 
};

SR_ s_4[] =
{
    { { REQ_TOKEN}, { 15} },                   
    { {       304}, { 16} }, // DeclList       
    { {       299}, { 17} }, // FuncDecl       
    { {       302}, { 18} }, // InitDecl       
    { {       300}, { 19} }, // PostFuncDecl   
    { {        42}, { 20} }, // '*'            
    { {        38}, { 21} }, // '&'            
    { {       301}, { 22} }, // Decl           
    { {       297}, { 23} }, // PrimaryFuncDecl
    { {       295}, { 24} }, // VarDecl        
    { {       284}, { 25} }, // ID             
    { {        40}, { 26} }, // '('            
    { {       296}, { 27} }, // PostVarDecl    
    { {       272}, { 28} }, // ID_TEXT        
    { {       294}, { 29} }, // PrimaryVarDecl 
    { {         0}, {  0} },                   
};

SR_ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR_ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR_ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR_ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR_ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR_ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR_ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR_ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR_ s_13[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       284}, { 30} }, // ID     
    { {       272}, { 28} }, // ID_TEXT
    { {         0}, {  0} },           
};

SR_ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -98} }, 
};

SR_ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -99} }, 
};

SR_ s_16[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 31} }, // ';'
    { {        44}, { 32} }, // ','
    { {         0}, {  0} },       
};

SR_ s_17[] =
{
    { { REQ_DEF}, {   2} },       
    { {     123}, {  33} }, // '{'
    { {       0}, { -73} },       
};

SR_ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR_ s_19[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  34} }, // '['
    { {       0}, { -69} },       
};

SR_ s_20[] =
{
    { { REQ_TOKEN}, { 12} },                   
    { {       299}, { 35} }, // FuncDecl       
    { {       295}, { 36} }, // VarDecl        
    { {       300}, { 19} }, // PostFuncDecl   
    { {        42}, { 20} }, // '*'            
    { {        38}, { 21} }, // '&'            
    { {       296}, { 27} }, // PostVarDecl    
    { {       297}, { 23} }, // PrimaryFuncDecl
    { {       294}, { 29} }, // PrimaryVarDecl 
    { {       284}, { 25} }, // ID             
    { {        40}, { 26} }, // '('            
    { {       272}, { 28} }, // ID_TEXT        
    { {         0}, {  0} },                   
};

SR_ s_21[] =
{
    { { REQ_TOKEN}, { 12} },                   
    { {       299}, { 37} }, // FuncDecl       
    { {       295}, { 38} }, // VarDecl        
    { {       300}, { 19} }, // PostFuncDecl   
    { {        42}, { 20} }, // '*'            
    { {        38}, { 21} }, // '&'            
    { {       296}, { 27} }, // PostVarDecl    
    { {       297}, { 23} }, // PrimaryFuncDecl
    { {       294}, { 29} }, // PrimaryVarDecl 
    { {       284}, { 25} }, // ID             
    { {        40}, { 26} }, // '('            
    { {       272}, { 28} }, // ID_TEXT        
    { {         0}, {  0} },                   
};

SR_ s_22[] =
{
    { { REQ_DEF}, {   2} },       
    { {      61}, {  39} }, // '='
    { {       0}, { -74} },       
};

SR_ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR_ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR_ s_25[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  40} }, // '('
    { {       0}, { -52} },       
};

SR_ s_26[] =
{
    { { ERR_REQ}, { 13} },                   
    { {     299}, { 41} }, // FuncDecl       
    { { errTok_}, { 42} }, // errTok_        
    { {     295}, { 43} }, // VarDecl        
    { {     300}, { 19} }, // PostFuncDecl   
    { {      42}, { 20} }, // '*'            
    { {      38}, { 21} }, // '&'            
    { {     296}, { 27} }, // PostVarDecl    
    { {     297}, { 23} }, // PrimaryFuncDecl
    { {     294}, { 29} }, // PrimaryVarDecl 
    { {     284}, { 25} }, // ID             
    { {      40}, { 26} }, // '('            
    { {     272}, { 28} }, // ID_TEXT        
    { {       0}, {  0} },                   
};

SR_ s_27[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  44} }, // '['
    { {       0}, { -59} },       
};

SR_ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR_ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR_ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR_ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -94} }, 
};

SR_ s_32[] =
{
    { { ERR_REQ}, { 15} },                   
    { {     302}, { 45} }, // InitDecl       
    { { errTok_}, { 46} }, // errTok_        
    { {     301}, { 22} }, // Decl           
    { {     295}, { 24} }, // VarDecl        
    { {     299}, { 47} }, // FuncDecl       
    { {     296}, { 27} }, // PostVarDecl    
    { {      42}, { 20} }, // '*'            
    { {      38}, { 21} }, // '&'            
    { {     300}, { 19} }, // PostFuncDecl   
    { {     294}, { 29} }, // PrimaryVarDecl 
    { {     297}, { 23} }, // PrimaryFuncDecl
    { {     284}, { 25} }, // ID             
    { {      40}, { 26} }, // '('            
    { {     272}, { 28} }, // ID_TEXT        
    { {       0}, {  0} },                   
};

SR_ s_33[] =
{
    { { ERR_REQ_DEF}, {   3} },                 
    { {         292}, {  48} }, // StatementList
    { {     errTok_}, {  49} }, // errTok_      
    { {           0}, { -44} },                 
};

SR_ s_34[] =
{
    { { ERR_REQ}, { 21} },                     
    { {      93}, { 50} }, // ']'              
    { {     286}, { 51} }, // Expression       
    { { errTok_}, { 52} }, // errTok_          
    { {     289}, { 53} }, // PreExpression    
    { {     287}, { 54} }, // PostExpression   
    { {      43}, { 55} }, // '+'              
    { {      45}, { 56} }, // '-'              
    { {      42}, { 57} }, // '*'              
    { {      38}, { 58} }, // '&'              
    { {     285}, { 59} }, // PrimaryExpression
    { {     265}, { 60} }, // TRUE             
    { {     266}, { 61} }, // FALSE            
    { {     273}, { 62} }, // CONSTINT         
    { {     274}, { 63} }, // CONSTINT_BIN     
    { {     275}, { 64} }, // CONSTINT_OCT     
    { {     276}, { 65} }, // CONSTINT_HEX     
    { {     277}, { 66} }, // CONSTFP          
    { {     284}, { 67} }, // ID               
    { {      40}, { 68} }, // '('              
    { {     272}, { 28} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR_ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR_ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR_ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR_ s_39[] =
{
    { { REQ_TOKEN}, { 19} },                     
    { {       286}, { 69} }, // Expression       
    { {       289}, { 53} }, // PreExpression    
    { {       287}, { 54} }, // PostExpression   
    { {        43}, { 55} }, // '+'              
    { {        45}, { 56} }, // '-'              
    { {        42}, { 57} }, // '*'              
    { {        38}, { 58} }, // '&'              
    { {       285}, { 59} }, // PrimaryExpression
    { {       265}, { 60} }, // TRUE             
    { {       266}, { 61} }, // FALSE            
    { {       273}, { 62} }, // CONSTINT         
    { {       274}, { 63} }, // CONSTINT_BIN     
    { {       275}, { 64} }, // CONSTINT_OCT     
    { {       276}, { 65} }, // CONSTINT_HEX     
    { {       277}, { 66} }, // CONSTFP          
    { {       284}, { 67} }, // ID               
    { {        40}, { 68} }, // '('              
    { {       272}, { 28} }, // ID_TEXT          
    { {         0}, {  0} },                     
};

SR_ s_40[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     298}, {  70} }, // OptParamList 
    { {     257}, {  71} }, // VOID         
    { {     305}, {  72} }, // ParamList    
    { {     303}, {  73} }, // TypePrimitive
    { {     258}, {   6} }, // BOOL         
    { {     259}, {   7} }, // CHAR         
    { {     260}, {   8} }, // SHORT        
    { {     261}, {   9} }, // INT          
    { {     262}, {  10} }, // LONG         
    { {     263}, {  11} }, // FLOAT        
    { {     264}, {  12} }, // DOUBLE       
    { {     271}, {  13} }, // STRUCT       
    { {       0}, { -88} },                 
};

SR_ s_41[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 74} }, // ')'
    { {         0}, {  0} },       
};

SR_ s_42[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 75} }, // ')'
    { {         0}, {  0} },       
};

SR_ s_43[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 76} }, // ')'
    { {         0}, {  0} },       
};

SR_ s_44[] =
{
    { { ERR_REQ}, { 21} },                     
    { {      93}, { 77} }, // ']'              
    { {     286}, { 78} }, // Expression       
    { { errTok_}, { 79} }, // errTok_          
    { {     289}, { 53} }, // PreExpression    
    { {     287}, { 54} }, // PostExpression   
    { {      43}, { 55} }, // '+'              
    { {      45}, { 56} }, // '-'              
    { {      42}, { 57} }, // '*'              
    { {      38}, { 58} }, // '&'              
    { {     285}, { 59} }, // PrimaryExpression
    { {     265}, { 60} }, // TRUE             
    { {     266}, { 61} }, // FALSE            
    { {     273}, { 62} }, // CONSTINT         
    { {     274}, { 63} }, // CONSTINT_BIN     
    { {     275}, { 64} }, // CONSTINT_OCT     
    { {     276}, { 65} }, // CONSTINT_HEX     
    { {     277}, { 66} }, // CONSTFP          
    { {     284}, { 67} }, // ID               
    { {      40}, { 68} }, // '('              
    { {     272}, { 28} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR_ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR_ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR_ s_48[] =
{
    { { ERR_REQ}, { 38} },                     
    { {     125}, { 80} }, // '}'              
    { {     290}, { 81} }, // Statement        
    { { errTok_}, { 82} }, // errTok_          
    { {      59}, { 83} }, // ';'              
    { {     286}, { 84} }, // Expression       
    { {     291}, { 85} }, // Declaration      
    { {     268}, { 86} }, // IF               
    { {     270}, { 87} }, // WHILE            
    { {     267}, { 88} }, // RETURN           
    { {     123}, { 89} }, // '{'              
    { {     289}, { 53} }, // PreExpression    
    { {     303}, {  4} }, // TypePrimitive    
    { {     287}, { 54} }, // PostExpression   
    { {      43}, { 55} }, // '+'              
    { {      45}, { 56} }, // '-'              
    { {      42}, { 57} }, // '*'              
    { {      38}, { 58} }, // '&'              
    { {     257}, {  5} }, // VOID             
    { {     258}, {  6} }, // BOOL             
    { {     259}, {  7} }, // CHAR             
    { {     260}, {  8} }, // SHORT            
    { {     261}, {  9} }, // INT              
    { {     262}, { 10} }, // LONG             
    { {     263}, { 11} }, // FLOAT            
    { {     264}, { 12} }, // DOUBLE           
    { {     271}, { 13} }, // STRUCT           
    { {     285}, { 59} }, // PrimaryExpression
    { {     265}, { 60} }, // TRUE             
    { {     266}, { 61} }, // FALSE            
    { {     273}, { 62} }, // CONSTINT         
    { {     274}, { 63} }, // CONSTINT_BIN     
    { {     275}, { 64} }, // CONSTINT_OCT     
    { {     276}, { 65} }, // CONSTINT_HEX     
    { {     277}, { 66} }, // CONSTFP          
    { {     284}, { 67} }, // ID               
    { {      40}, { 68} }, // '('              
    { {     272}, { 28} }, // ID_TEXT          
    { {       0}, {  0} },                     
};

SR_ s_49[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 90} }, // '}'
    { {         0}, {  0} },       
};

SR_ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR_ s_51[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        93}, {  91} }, // ']'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_52[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 103} }, // ']'
    { {         0}, {   0} },       
};

SR_ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR_ s_54[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, { 104} }, // '('
    { {       0}, { -16} },       
};

SR_ s_55[] =
{
    { { REQ_TOKEN}, {  18} },                     
    { {       289}, { 105} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_56[] =
{
    { { REQ_TOKEN}, {  18} },                     
    { {       289}, { 106} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, {  18} },                     
    { {       289}, { 107} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_58[] =
{
    { { REQ_TOKEN}, {  18} },                     
    { {       289}, { 108} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR_ s_60[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_61[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR_ s_62[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_63[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR_ s_64[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_65[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_66[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR_ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR_ s_68[] =
{
    { { ERR_REQ}, {  20} },                     
    { {     286}, { 109} }, // Expression       
    { { errTok_}, { 110} }, // errTok_          
    { {     289}, {  53} }, // PreExpression    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_69[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  92} }, // '='
    { {      60}, {  93} }, // '<'
    { {      62}, {  94} }, // '>'
    { {     278}, {  95} }, // LE 
    { {     279}, {  96} }, // GE 
    { {     280}, {  97} }, // EQ 
    { {     281}, {  98} }, // NE 
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -75} },       
};

SR_ s_70[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 111} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_71[] =
{
    { { REQ_DEF}, {   2} },       
    { {      41}, { -89} }, // ')'
    { {       0}, { -76} },       
};

SR_ s_72[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 112} }, // ','
    { {       0}, { -90} },       
};

SR_ s_73[] =
{
    { { REQ_TOKEN}, {  13} },                   
    { {       301}, { 113} }, // Decl           
    { {       295}, {  24} }, // VarDecl        
    { {       299}, {  47} }, // FuncDecl       
    { {       296}, {  27} }, // PostVarDecl    
    { {        42}, {  20} }, // '*'            
    { {        38}, {  21} }, // '&'            
    { {       300}, {  19} }, // PostFuncDecl   
    { {       294}, {  29} }, // PrimaryVarDecl 
    { {       297}, {  23} }, // PrimaryFuncDecl
    { {       284}, {  25} }, // ID             
    { {        40}, {  26} }, // '('            
    { {       272}, {  28} }, // ID_TEXT        
    { {         0}, {   0} },                   
};

SR_ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR_ s_75[] =
{
    { { REQ_DEF}, {   2} },       
    { {     123}, { -64} }, // '{'
    { {       0}, { -54} },       
};

SR_ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR_ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR_ s_78[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        93}, { 114} }, // ']'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 115} }, // ']'
    { {         0}, {   0} },       
};

SR_ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -95} }, 
};

SR_ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR_ s_82[] =
{
    { { REQ_DEF}, {   2} },       
    { {      59}, { 116} }, // ';'
    { {       0}, { -46} },       
};

SR_ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR_ s_84[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        59}, { 117} }, // ';'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR_ s_86[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        40}, { 118} }, // '('
    { {         0}, {   0} },       
};

SR_ s_87[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        40}, { 119} }, // '('
    { {         0}, {   0} },       
};

SR_ s_88[] =
{
    { { REQ_TOKEN}, {  20} },                     
    { {        59}, { 120} }, // ';'              
    { {       286}, { 121} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_89[] =
{
    { { ERR_REQ_DEF}, {   3} },                 
    { {         292}, { 122} }, // StatementList
    { {     errTok_}, { 123} }, // errTok_      
    { {           0}, { -44} },                 
};

SR_ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -96} }, 
};

SR_ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR_ s_92[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 124} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_93[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 125} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_94[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 126} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_95[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 127} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_96[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 128} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_97[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 129} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_98[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 130} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_99[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 131} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_100[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 132} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_101[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 133} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_102[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 134} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR_ s_104[] =
{
    { { ERR_REQ_DEF}, {  22} },                     
    { {         288}, { 135} }, // OptArgList       
    { {     errTok_}, { 136} }, // errTok_          
    { {         293}, { 137} }, // ArgList          
    { {         286}, { 138} }, // Expression       
    { {         289}, {  53} }, // PreExpression    
    { {         287}, {  54} }, // PostExpression   
    { {          43}, {  55} }, // '+'              
    { {          45}, {  56} }, // '-'              
    { {          42}, {  57} }, // '*'              
    { {          38}, {  58} }, // '&'              
    { {         285}, {  59} }, // PrimaryExpression
    { {         265}, {  60} }, // TRUE             
    { {         266}, {  61} }, // FALSE            
    { {         273}, {  62} }, // CONSTINT         
    { {         274}, {  63} }, // CONSTINT_BIN     
    { {         275}, {  64} }, // CONSTINT_OCT     
    { {         276}, {  65} }, // CONSTINT_HEX     
    { {         277}, {  66} }, // CONSTFP          
    { {         284}, {  67} }, // ID               
    { {          40}, {  68} }, // '('              
    { {         272}, {  28} }, // ID_TEXT          
    { {           0}, { -47} },                     
};

SR_ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR_ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR_ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR_ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR_ s_109[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 139} }, // ')'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_110[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 140} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR_ s_112[] =
{
    { { ERR_REQ}, {  12} },                 
    { {     303}, { 141} }, // TypePrimitive
    { { errTok_}, { 142} }, // errTok_      
    { {     257}, {   5} }, // VOID         
    { {     258}, {   6} }, // BOOL         
    { {     259}, {   7} }, // CHAR         
    { {     260}, {   8} }, // SHORT        
    { {     261}, {   9} }, // INT          
    { {     262}, {  10} }, // LONG         
    { {     263}, {  11} }, // FLOAT        
    { {     264}, {  12} }, // DOUBLE       
    { {     271}, {  13} }, // STRUCT       
    { {       0}, {   0} },                 
};

SR_ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR_ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR_ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR_ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR_ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR_ s_118[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 143} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_119[] =
{
    { { REQ_TOKEN}, {  19} },                     
    { {       286}, { 144} }, // Expression       
    { {       289}, {  53} }, // PreExpression    
    { {       287}, {  54} }, // PostExpression   
    { {        43}, {  55} }, // '+'              
    { {        45}, {  56} }, // '-'              
    { {        42}, {  57} }, // '*'              
    { {        38}, {  58} }, // '&'              
    { {       285}, {  59} }, // PrimaryExpression
    { {       265}, {  60} }, // TRUE             
    { {       266}, {  61} }, // FALSE            
    { {       273}, {  62} }, // CONSTINT         
    { {       274}, {  63} }, // CONSTINT_BIN     
    { {       275}, {  64} }, // CONSTINT_OCT     
    { {       276}, {  65} }, // CONSTINT_HEX     
    { {       277}, {  66} }, // CONSTFP          
    { {       284}, {  67} }, // ID               
    { {        40}, {  68} }, // '('              
    { {       272}, {  28} }, // ID_TEXT          
    { {         0}, {   0} },                     
};

SR_ s_120[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR_ s_121[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        59}, { 145} }, // ';'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_122[] =
{
    { { ERR_REQ}, {  38} },                     
    { {     125}, { 146} }, // '}'              
    { {     290}, {  81} }, // Statement        
    { { errTok_}, {  82} }, // errTok_          
    { {      59}, {  83} }, // ';'              
    { {     286}, {  84} }, // Expression       
    { {     291}, {  85} }, // Declaration      
    { {     268}, {  86} }, // IF               
    { {     270}, {  87} }, // WHILE            
    { {     267}, {  88} }, // RETURN           
    { {     123}, {  89} }, // '{'              
    { {     289}, {  53} }, // PreExpression    
    { {     303}, {   4} }, // TypePrimitive    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // BOOL             
    { {     259}, {   7} }, // CHAR             
    { {     260}, {   8} }, // SHORT            
    { {     261}, {   9} }, // INT              
    { {     262}, {  10} }, // LONG             
    { {     263}, {  11} }, // FLOAT            
    { {     264}, {  12} }, // DOUBLE           
    { {     271}, {  13} }, // STRUCT           
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_123[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 147} }, // '}'
    { {         0}, {   0} },       
};

SR_ s_124[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  92} }, // '='
    { {      60}, {  93} }, // '<'
    { {      62}, {  94} }, // '>'
    { {     278}, {  95} }, // LE 
    { {     279}, {  96} }, // GE 
    { {     280}, {  97} }, // EQ 
    { {     281}, {  98} }, // NE 
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -22} },       
};

SR_ s_125[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -23} },       
};

SR_ s_126[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -24} },       
};

SR_ s_127[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -25} },       
};

SR_ s_128[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -26} },       
};

SR_ s_129[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -27} },       
};

SR_ s_130[] =
{
    { { REQ_DEF}, {   5} },       
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -28} },       
};

SR_ s_131[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -29} },       
};

SR_ s_132[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -30} },       
};

SR_ s_133[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR_ s_134[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -32} }, 
};

SR_ s_135[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 148} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_136[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 149} }, // ')'
    { {         0}, {   0} },       
};

SR_ s_137[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 150} }, // ','
    { {       0}, { -48} },       
};

SR_ s_138[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  92} }, // '='
    { {      60}, {  93} }, // '<'
    { {      62}, {  94} }, // '>'
    { {     278}, {  95} }, // LE 
    { {     279}, {  96} }, // GE 
    { {     280}, {  97} }, // EQ 
    { {     281}, {  98} }, // NE 
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -49} },       
};

SR_ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR_ s_141[] =
{
    { { REQ_TOKEN}, {  13} },                   
    { {       301}, { 151} }, // Decl           
    { {       295}, {  24} }, // VarDecl        
    { {       299}, {  47} }, // FuncDecl       
    { {       296}, {  27} }, // PostVarDecl    
    { {        42}, {  20} }, // '*'            
    { {        38}, {  21} }, // '&'            
    { {       300}, {  19} }, // PostFuncDecl   
    { {       294}, {  29} }, // PrimaryVarDecl 
    { {       297}, {  23} }, // PrimaryFuncDecl
    { {       284}, {  25} }, // ID             
    { {        40}, {  26} }, // '('            
    { {       272}, {  28} }, // ID_TEXT        
    { {         0}, {   0} },                   
};

SR_ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -93} }, 
};

SR_ s_143[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 152} }, // ')'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_144[] =
{
    { { REQ_TOKEN}, {  13} },       
    { {        41}, { 153} }, // ')'
    { {        61}, {  92} }, // '='
    { {        60}, {  93} }, // '<'
    { {        62}, {  94} }, // '>'
    { {       278}, {  95} }, // LE 
    { {       279}, {  96} }, // GE 
    { {       280}, {  97} }, // EQ 
    { {       281}, {  98} }, // NE 
    { {        43}, {  99} }, // '+'
    { {        45}, { 100} }, // '-'
    { {        42}, { 101} }, // '*'
    { {        47}, { 102} }, // '/'
    { {         0}, {   0} },       
};

SR_ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR_ s_146[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR_ s_147[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR_ s_148[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR_ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR_ s_150[] =
{
    { { ERR_REQ}, {  20} },                     
    { {     286}, { 154} }, // Expression       
    { { errTok_}, { 155} }, // errTok_          
    { {     289}, {  53} }, // PreExpression    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_151[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -92} }, 
};

SR_ s_152[] =
{
    { { ERR_REQ}, {  37} },                     
    { {     290}, { 156} }, // Statement        
    { {      59}, {  83} }, // ';'              
    { { errTok_}, { 157} }, // errTok_          
    { {     286}, {  84} }, // Expression       
    { {     291}, {  85} }, // Declaration      
    { {     268}, {  86} }, // IF               
    { {     270}, {  87} }, // WHILE            
    { {     267}, {  88} }, // RETURN           
    { {     123}, {  89} }, // '{'              
    { {     289}, {  53} }, // PreExpression    
    { {     303}, {   4} }, // TypePrimitive    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // BOOL             
    { {     259}, {   7} }, // CHAR             
    { {     260}, {   8} }, // SHORT            
    { {     261}, {   9} }, // INT              
    { {     262}, {  10} }, // LONG             
    { {     263}, {  11} }, // FLOAT            
    { {     264}, {  12} }, // DOUBLE           
    { {     271}, {  13} }, // STRUCT           
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_153[] =
{
    { { ERR_REQ}, {  37} },                     
    { {     290}, { 158} }, // Statement        
    { {      59}, {  83} }, // ';'              
    { { errTok_}, { 157} }, // errTok_          
    { {     286}, {  84} }, // Expression       
    { {     291}, {  85} }, // Declaration      
    { {     268}, {  86} }, // IF               
    { {     270}, {  87} }, // WHILE            
    { {     267}, {  88} }, // RETURN           
    { {     123}, {  89} }, // '{'              
    { {     289}, {  53} }, // PreExpression    
    { {     303}, {   4} }, // TypePrimitive    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // BOOL             
    { {     259}, {   7} }, // CHAR             
    { {     260}, {   8} }, // SHORT            
    { {     261}, {   9} }, // INT              
    { {     262}, {  10} }, // LONG             
    { {     263}, {  11} }, // FLOAT            
    { {     264}, {  12} }, // DOUBLE           
    { {     271}, {  13} }, // STRUCT           
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_154[] =
{
    { { REQ_DEF}, {  12} },       
    { {      61}, {  92} }, // '='
    { {      60}, {  93} }, // '<'
    { {      62}, {  94} }, // '>'
    { {     278}, {  95} }, // LE 
    { {     279}, {  96} }, // GE 
    { {     280}, {  97} }, // EQ 
    { {     281}, {  98} }, // NE 
    { {      43}, {  99} }, // '+'
    { {      45}, { 100} }, // '-'
    { {      42}, { 101} }, // '*'
    { {      47}, { 102} }, // '/'
    { {       0}, { -50} },       
};

SR_ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR_ s_156[] =
{
    { { REQ_DEF}, {   2} },        
    { {     269}, { 159} }, // ELSE
    { {       0}, { -37} },        
};

SR_ s_157[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 116} }, // ';'
    { {         0}, {   0} },       
};

SR_ s_158[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR_ s_159[] =
{
    { { ERR_REQ}, {  37} },                     
    { {     290}, { 160} }, // Statement        
    { {      59}, {  83} }, // ';'              
    { { errTok_}, { 157} }, // errTok_          
    { {     286}, {  84} }, // Expression       
    { {     291}, {  85} }, // Declaration      
    { {     268}, {  86} }, // IF               
    { {     270}, {  87} }, // WHILE            
    { {     267}, {  88} }, // RETURN           
    { {     123}, {  89} }, // '{'              
    { {     289}, {  53} }, // PreExpression    
    { {     303}, {   4} }, // TypePrimitive    
    { {     287}, {  54} }, // PostExpression   
    { {      43}, {  55} }, // '+'              
    { {      45}, {  56} }, // '-'              
    { {      42}, {  57} }, // '*'              
    { {      38}, {  58} }, // '&'              
    { {     257}, {   5} }, // VOID             
    { {     258}, {   6} }, // BOOL             
    { {     259}, {   7} }, // CHAR             
    { {     260}, {   8} }, // SHORT            
    { {     261}, {   9} }, // INT              
    { {     262}, {  10} }, // LONG             
    { {     263}, {  11} }, // FLOAT            
    { {     264}, {  12} }, // DOUBLE           
    { {     271}, {  13} }, // STRUCT           
    { {     285}, {  59} }, // PrimaryExpression
    { {     265}, {  60} }, // TRUE             
    { {     266}, {  61} }, // FALSE            
    { {     273}, {  62} }, // CONSTINT         
    { {     274}, {  63} }, // CONSTINT_BIN     
    { {     275}, {  64} }, // CONSTINT_OCT     
    { {     276}, {  65} }, // CONSTINT_HEX     
    { {     277}, {  66} }, // CONSTFP          
    { {     284}, {  67} }, // ID               
    { {      40}, {  68} }, // '('              
    { {     272}, {  28} }, // ID_TEXT          
    { {       0}, {   0} },                     
};

SR_ s_160[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void ParserBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void ParserBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void ParserBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = std::move(d_next.second);

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void ParserBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void ParserBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Parser::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
        { _Root = std::move(vs_(0)); }
        break;

        case 2:
        { d_val_ = std::make_unique<ast::ID>(_Scanner->matched(), _Scanner->GetLocation()); }
        break;

        case 3:
        { d_val_ = std::make_unique<ast::Constant>(true, _Scanner->GetLocation()); }
        break;

        case 4:
        { d_val_ = std::make_unique<ast::Constant>(false, _Scanner->GetLocation()); }
        break;

        case 5:
        { d_val_ = std::make_unique<ast::Constant>(std::stoll(_Scanner->matched()), _Scanner->GetLocation()); }
        break;

        case 6:
        { d_val_ = std::make_unique<ast::Constant>(std::stoll(_Scanner->matched(), nullptr, 2), _Scanner->GetLocation()); }
        break;

        case 7:
        { d_val_ = std::make_unique<ast::Constant>(std::stoll(_Scanner->matched(), nullptr, 8), _Scanner->GetLocation()); }
        break;

        case 8:
        { d_val_ = std::make_unique<ast::Constant>(std::stoll(_Scanner->matched(), nullptr, 16), _Scanner->GetLocation()); }
        break;

        case 9:
        { d_val_ = std::make_unique<ast::Constant>(std::stod(_Scanner->matched()), _Scanner->GetLocation()); }
        break;

        case 10:
        { d_val_ = std::make_unique<ast::Variable>(vs_(0)); }
        break;

        case 11:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 12:
        { d_val_ = nullptr; }
        break;

        case 13:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 14:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::CallExpr>(d_val_)->SetFunc(vs_(-3)); }
        break;

        case 15:
        { d_val_ = nullptr; }
        break;

        case 16:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 17:
        { d_val_ = std::make_unique<ast::UnOpExpr>(vs_(0), ast::UnOpExpr::POS); }
        break;

        case 18:
        { d_val_ = std::make_unique<ast::UnOpExpr>(vs_(0), ast::UnOpExpr::NEG); }
        break;

        case 19:
        { d_val_ = std::make_unique<ast::UnOpExpr>(vs_(0), ast::UnOpExpr::DEREF); }
        break;

        case 20:
        { d_val_ = std::make_unique<ast::UnOpExpr>(vs_(0), ast::UnOpExpr::ADDR); }
        break;

        case 21:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 22:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::ASSIGN); }
        break;

        case 23:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::LESS); }
        break;

        case 24:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::GREATER); }
        break;

        case 25:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::LESS_EQUAL); }
        break;

        case 26:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::GREATER_EQUAL); }
        break;

        case 27:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::EQUAL); }
        break;

        case 28:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::NOT_EQUAL); }
        break;

        case 29:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::ADD); }
        break;

        case 30:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::SUB); }
        break;

        case 31:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::MUL); }
        break;

        case 32:
        { d_val_ = std::make_unique<ast::BiOpExpr>(vs_(-2), vs_(0), ast::BiOpExpr::DIV); }
        break;

        case 33:
        { d_val_ = std::make_unique<ast::ExprStmt>(); }
        break;

        case 34:
        { d_val_ = nullptr; }
        break;

        case 35:
        { d_val_ = std::make_unique<ast::ExprStmt>(vs_(-1)); }
        break;

        case 36:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 37:
        { d_val_ = std::make_unique<ast::IfStmt>(vs_(-2), vs_(0)); }
        break;

        case 38:
        { d_val_ = std::make_unique<ast::IfStmt>(vs_(-4), vs_(-2), vs_(0)); }
        break;

        case 39:
        { d_val_ = std::make_unique<ast::WhileStmt>(vs_(-2), vs_(0)); }
        break;

        case 40:
        { d_val_ = std::make_unique<ast::ReturnStmt>(); }
        break;

        case 41:
        { d_val_ = std::make_unique<ast::ReturnStmt>(vs_(-1)); }
        break;

        case 42:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 43:
        { d_val_ = nullptr; }
        break;

        case 44:
        { d_val_ = std::make_unique<ast::StatementList>(); }
        break;

        case 45:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::StatementList>(d_val_)->AddStmt(vs_(0)); }
        break;

        case 46:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 47:
        { d_val_ = std::make_unique<ast::CallExpr>(); }
        break;

        case 48:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 49:
        { d_val_ = std::make_unique<ast::CallExpr>(vs_(0)); }
        break;

        case 50:
        { d_val_ = std::move(vs_(-2)); ast::cast<ast::CallExpr>(d_val_)->AddArg(vs_(0)); }
        break;

        case 51:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 52:
        { d_val_ = std::make_unique<ast::VarDecl>(vs_(0)); }
        break;

        case 53:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 54:
        { d_val_ = nullptr; }
        break;

        case 55:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 56:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-2)); }
        break;

        case 57:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-3), vs_(-1)); }
        break;

        case 58:
        { d_val_ = nullptr; }
        break;

        case 59:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 60:
        { d_val_ = std::make_unique<ast::PointerDecl>(vs_(0)); }
        break;

        case 61:
        { d_val_ = std::make_unique<ast::ReferenceDecl>(vs_(0)); }
        break;

        case 62:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::FuncDecl>(d_val_)->SetName(vs_(-3)); }
        break;

        case 63:
        { d_val_ = std::move(vs_(-1)); }
        break;

        case 64:
        { d_val_ = nullptr; }
        break;

        case 65:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 66:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-2)); }
        break;

        case 67:
        { d_val_ = std::make_unique<ast::ArrayDecl>(vs_(-3), vs_(-1)); }
        break;

        case 68:
        { d_val_ = nullptr; }
        break;

        case 69:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 70:
        { d_val_ = std::make_unique<ast::PointerDecl>(vs_(0)); }
        break;

        case 71:
        { d_val_ = std::make_unique<ast::ReferenceDecl>(vs_(0)); }
        break;

        case 72:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 73:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 74:
        { d_val_ = std::make_unique<ast::InitDecl>(vs_(0)); }
        break;

        case 75:
        { d_val_ = std::make_unique<ast::InitDecl>(vs_(-2), vs_(0)); }
        break;

        case 76:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::VOID); }
        break;

        case 77:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::BOOL); }
        break;

        case 78:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::CHAR); }
        break;

        case 79:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::SHORT); }
        break;

        case 80:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::INT); }
        break;

        case 81:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::LONG); }
        break;

        case 82:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::FLOAT); }
        break;

        case 83:
        { d_val_ = std::make_unique<ast::BasicType>(ast::BasicType::DOUBLE); }
        break;

        case 84:
        { d_val_ = std::make_unique<ast::CustomType>(vs_(0)); }
        break;

        case 85:
        { d_val_ = std::make_unique<ast::VarDeclaration>(vs_(0)); }
        break;

        case 86:
        { d_val_ = std::move(vs_(-2)); ast::cast<ast::VarDeclaration>(d_val_)->AddVar(vs_(0)); }
        break;

        case 87:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 88:
        { d_val_ = std::make_unique<ast::FuncDecl>(); }
        break;

        case 89:
        { d_val_ = std::make_unique<ast::FuncDecl>(); }
        break;

        case 90:
        { d_val_ = std::move(vs_(0)); }
        break;

        case 91:
        { d_val_ = std::make_unique<ast::FuncDecl>(vs_(-1), vs_(0)); }
        break;

        case 92:
        { d_val_ = std::move(vs_(-3)); ast::cast<ast::FuncDecl>(d_val_)->AddParam(vs_(-1), vs_(0)); }
        break;

        case 93:
        { d_val_ = std::move(vs_(-2)); }
        break;

        case 94:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::VarDeclaration>(d_val_)->SetType(vs_(-2)); }
        break;

        case 95:
        { d_val_ = std::make_unique<ast::FuncDeclaration>(vs_(-4), vs_(-3), vs_(-1)); }
        break;

        case 96:
        { d_val_ = nullptr; }
        break;

        case 97:
        { d_val_ = std::make_unique<ast::DeclarationList>(vs_(0)); }
        break;

        case 98:
        { d_val_ = std::move(vs_(-1)); ast::cast<ast::DeclarationList>(d_val_)->AddDecl(vs_(0)); }
        break;

        case 99:
        { d_val_ = std::move(vs_(-1)); }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Parser::print_()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


// This function will be appended to parse.cc

std::vector<int> Parser::ValidTokens()
{
    auto sr = s_state[state_()];
    auto last = sr + sr->d_lastIdx;
    std::set<int> set;
    std::vector<int> res;
    for (; ++sr != last;)
        if (sr->d_token > 0 && sr->d_token != 256 && 
            sr->d_token < 257 + static_cast<int>(TOKEN_COUNT) &&
            set.find(sr->d_token) == set.end())
        {
            set.insert(sr->d_token);
            res.push_back(sr->d_token);
        }
    if (sr == last && sr->d_action < 0)
        if (sr->d_token > 0 && sr->d_token != 256 && 
            sr->d_token < 257 + static_cast<int>(TOKEN_COUNT) &&
            set.find(sr->d_token) == set.end())
        {
            set.insert(sr->d_token);
            res.push_back(sr->d_token);
        }
    return res;
}
