     Token        Matched       Row  ColStart    ColEnd

       INT            int         1         1         4
   ID_TEXT        getchar         1         5        12
      CHAR              (         1        12        13
      CHAR              )         1        13        14
      CHAR              ;         1        14        15
       INT            int         2         1         4
   ID_TEXT        putchar         2         5        12
      CHAR              (         2        12        13
       INT            int         2        13        16
   ID_TEXT             ch         2        17        19
      CHAR              )         2        19        20
      CHAR              ;         2        20        21
      VOID           void         4         1         5
   ID_TEXT         output         4         6        12
      CHAR              (         4        12        13
       INT            int         4        13        16
   ID_TEXT              n         4        17        18
      CHAR              )         4        18        19
      CHAR              {         5         1         2
        IF             if         6         5         7
      CHAR              (         6         8         9
   ID_TEXT              n         6         9        10
      CHAR              <         6        11        12
  CONSTINT              0         6        13        14
      CHAR              )         6        14        15
      CHAR              {         7         5         6
   ID_TEXT        putchar         8         9        16
      CHAR              (         8        16        17
 CONSTCHAR            '-'         8        17        20
      CHAR              )         8        20        21
      CHAR              ;         8        21        22
   ID_TEXT              n         9         9        10
      CHAR              =         9        11        12
      CHAR              -         9        13        14
   ID_TEXT              n         9        14        15
      CHAR              ;         9        15        16
      CHAR              }        10         5         6
      ELSE           else        11         5         9
        IF             if        11        10        12
      CHAR              (        11        13        14
   ID_TEXT              n        11        14        15
        EQ             ==        11        16        18
  CONSTINT              0        11        19        20
      CHAR              )        11        20        21
      CHAR              {        12         5         6
   ID_TEXT        putchar        13         9        16
      CHAR              (        13        16        17
 CONSTCHAR            '0'        13        17        20
      CHAR              )        13        20        21
      CHAR              ;        13        21        22
    RETURN         return        14         9        15
      CHAR              ;        14        15        16
      CHAR              }        15         5         6
       INT            int        16         5         8
   ID_TEXT            num        16         9        12
      CHAR              [        16        12        13
  CONSTINT             20        16        13        15
      CHAR              ]        16        15        16
      CHAR              ,        16        16        17
   ID_TEXT            idx        16        18        21
      CHAR              =        16        22        23
  CONSTINT              0        16        24        25
      CHAR              ;        16        25        26
     WHILE          while        17         5        10
      CHAR              (        17        11        12
   ID_TEXT              n        17        12        13
        NE             !=        17        14        16
  CONSTINT              0        17        17        18
      CHAR              )        17        18        19
      CHAR              {        18         5         6
   ID_TEXT            num        19         9        12
      CHAR              [        19        12        13
   ID_TEXT            idx        19        13        16
      CHAR              ]        19        16        17
      CHAR              =        19        18        19
   ID_TEXT              n        19        20        21
      CHAR              %        19        22        23
  CONSTINT             10        19        24        26
      CHAR              ;        19        26        27
   ID_TEXT              n        20         9        10
DIV_ASSIGN             /=        20        11        13
  CONSTINT             10        20        14        16
      CHAR              ;        20        16        17
       INC             ++        21         9        11
   ID_TEXT            idx        21        11        14
      CHAR              ;        21        14        15
      CHAR              }        22         5         6
       FOR            for        23         5         8
      CHAR              (        23         9        10
       DEC             --        23        10        12
   ID_TEXT            idx        23        12        15
      CHAR              ;        23        15        16
   ID_TEXT            idx        23        17        20
        GE             >=        23        21        23
  CONSTINT              0        23        24        25
      CHAR              ;        23        25        26
       DEC             --        23        27        29
   ID_TEXT            idx        23        29        32
      CHAR              )        23        32        33
   ID_TEXT        putchar        24         9        16
      CHAR              (        24        16        17
   ID_TEXT            num        24        17        20
      CHAR              [        24        20        21
   ID_TEXT            idx        24        21        24
      CHAR              ]        24        24        25
      CHAR              +        24        26        27
 CONSTCHAR            '0'        24        28        31
      CHAR              )        24        31        32
      CHAR              ;        24        32        33
      CHAR              }        25         1         2
       INT            int        27         1         4
   ID_TEXT          input        27         5        10
      CHAR              (        27        10        11
      CHAR              )        27        11        12
      CHAR              {        28         1         2
       INT            int        29         5         8
   ID_TEXT              n        29         9        10
      CHAR              =        29        11        12
  CONSTINT              0        29        13        14
      CHAR              ,        29        14        15
   ID_TEXT              t        29        16        17
      CHAR              =        29        18        19
   ID_TEXT        getchar        29        20        27
      CHAR              (        29        27        28
      CHAR              )        29        28        29
      CHAR              ;        29        29        30
     WHILE          while        30         5        10
      CHAR              (        30        11        12
 CONSTCHAR            '0'        30        12        15
        LE             <=        30        16        18
   ID_TEXT              t        30        19        20
      CHAR              &        30        21        22
   ID_TEXT              t        30        23        24
        LE             <=        30        25        27
 CONSTCHAR            '9'        30        28        31
      CHAR              )        30        31        32
      CHAR              {        31         5         6
   ID_TEXT              n        32         9        10
      CHAR              =        32        11        12
   ID_TEXT              n        32        13        14
      CHAR              *        32        15        16
  CONSTINT             10        32        17        19
      CHAR              +        32        20        21
   ID_TEXT              t        32        22        23
      CHAR              -        32        24        25
 CONSTCHAR            '0'        32        26        29
      CHAR              ;        32        29        30
   ID_TEXT              t        33         9        10
      CHAR              =        33        11        12
   ID_TEXT        getchar        33        13        20
      CHAR              (        33        20        21
      CHAR              )        33        21        22
      CHAR              ;        33        22        23
      CHAR              }        34         5         6
    RETURN         return        35         5        11
   ID_TEXT              n        35        12        13
      CHAR              ;        35        13        14
      CHAR              }        36         1         2
       INT            int        38         1         4
   ID_TEXT            div        38         5         8
      CHAR              (        38         8         9
       INT            int        38         9        12
   ID_TEXT              x        38        13        14
      CHAR              )        38        14        15
      CHAR              {        39         1         2
       INT            int        40         6         9
   ID_TEXT         factor        40        10        16
      CHAR              ;        40        16        17
   ID_TEXT         factor        42         6        12
      CHAR              =        42        13        14
  CONSTINT             10        42        15        17
      CHAR              ;        42        17        18
    RETURN         return        43         6        12
      CHAR              (        43        13        14
   ID_TEXT              x        43        14        15
      CHAR              /        43        15        16
   ID_TEXT         factor        43        16        22
      CHAR              )        43        22        23
      CHAR              ;        43        23        24
      CHAR              }        44         1         2
       INT            int        46         1         4
   ID_TEXT            rem        46         5         8
      CHAR              (        46         8         9
       INT            int        46         9        12
   ID_TEXT              x        46        13        14
      CHAR              ,        46        14        15
       INT            int        46        16        19
   ID_TEXT              y        46        20        21
      CHAR              )        46        21        22
      CHAR              {        47         1         2
       INT            int        48         4         7
   ID_TEXT         factor        48         8        14
      CHAR              ;        48        14        15
   ID_TEXT         factor        50         4        10
      CHAR              =        50        11        12
  CONSTINT             10        50        12        14
      CHAR              ;        50        14        15
    RETURN         return        51         4        10
      CHAR              (        51        11        12
   ID_TEXT              y        51        12        13
      CHAR              -        51        14        15
      CHAR              (        51        16        17
   ID_TEXT         factor        51        17        23
      CHAR              *        51        23        24
   ID_TEXT              x        51        24        25
      CHAR              )        51        25        26
      CHAR              )        51        26        27
      CHAR              ;        51        27        28
      CHAR              }        52         1         2
      VOID           void        54         1         5
   ID_TEXT           main        54         6        10
      CHAR              (        54        10        11
      VOID           void        54        11        15
      CHAR              )        54        15        16
      CHAR              {        55         1         2
       INT            int        57         2         5
   ID_TEXT              x        57         6         7
      CHAR              ;        57         7         8
       INT            int        58         2         5
   ID_TEXT             dx        58         6         8
      CHAR              ;        58         8         9
       INT            int        59         8        11
   ID_TEXT             rx        59        13        15
      CHAR              ;        59        15        16
   ID_TEXT              x        61         2         3
      CHAR              =        61         4         5
   ID_TEXT          input        61         6        11
      CHAR              (        61        11        12
      CHAR              )        61        12        13
      CHAR              ;        61        13        14
     WHILE          while        63         8        13
      CHAR              (        63        14        15
   ID_TEXT              x        63        15        16
      CHAR              >        63        17        18
  CONSTINT              0        63        19        20
      CHAR              )        63        20        21
      CHAR              {        64         7         8
   ID_TEXT             dx        65        11        13
      CHAR              =        65        14        15
   ID_TEXT            div        65        16        19
      CHAR              (        65        19        20
   ID_TEXT              x        65        20        21
      CHAR              )        65        21        22
      CHAR              ;        65        22        23
   ID_TEXT             rx        66         6         8
      CHAR              =        66         9        10
   ID_TEXT            rem        66        11        14
      CHAR              (        66        14        15
   ID_TEXT             dx        66        15        17
      CHAR              ,        66        17        18
   ID_TEXT              x        66        18        19
      CHAR              )        66        19        20
      CHAR              ;        66        20        21
   ID_TEXT         output        67        12        18
      CHAR              (        67        18        19
   ID_TEXT             rx        67        19        21
      CHAR              )        67        21        22
      CHAR              ;        67        22        23
   ID_TEXT              x        68         6         7
      CHAR              =        68         8         9
   ID_TEXT             dx        68        10        12
      CHAR              ;        68        12        13
      CHAR              }        69         8         9
      CHAR              }        70         1         2
